;;; disco-avatar-test.el --- Tests for shared Discord avatars -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(let ((load-prefer-newer t))
  (require 'disco-avatar))

(ert-deftest disco-avatar-user-identity-addresses-cdn-cache-and-resource ()
  (let* ((disco-avatar-image-size 28)
         (user '((id . "123") (avatar . "hash")
                 (discriminator . "4321"))))
    (should (equal "https://cdn.discordapp.com/avatars/123/hash.png?size=64"
                   (disco-avatar-url user)))
    (should (equal "123:hash:28" (disco-avatar-cache-key user)))
    (should (equal '(:avatar "123:hash:28")
                   (disco-avatar-resource-key user)))
    (should-not (disco-avatar-url '((avatar . "hash"))))
    (should-not (disco-avatar-cache-key '((avatar . "hash"))))))

(ert-deftest disco-avatar-default-bucket-preserves-legacy-discriminator ()
  (let ((user '((id . "123") (discriminator . "1234"))))
    (should (= 4 (disco-avatar--default-index user)))
    (should (equal "https://cdn.discordapp.com/embed/avatars/4.png"
                   (disco-avatar-url user)))))

(ert-deftest disco-avatar-default-bucket-is-exact-for-high-snowflake ()
  (let* ((snowflake "18446744073709551615")
         (parsed (string-to-number snowflake))
         (user `((id . ,snowflake) (discriminator . "0"))))
    ;; Discord snowflakes exceed signed int64.  The bucket calculation must
    ;; stay on Emacs bignums; a float conversion loses the low shifted bits.
    (should (integerp parsed))
    (should-not (floatp parsed))
    (should (= 18446744073709551615 parsed))
    (should (= 4398046511103 (ash parsed -22)))
    (should (= 3 (disco-avatar--default-index user)))
    (should (equal "https://cdn.discordapp.com/embed/avatars/3.png"
                   (disco-avatar-url user)))))

(ert-deftest disco-avatar-http-retry-policy-is-explicit ()
  (dolist (status '(nil 0 408 425 429 500 502 503))
    (should (disco-avatar--transient-http-status-p status)))
  (dolist (status '(400 401 403 404))
    (should-not (disco-avatar--transient-http-status-p status))))

(ert-deftest disco-avatar-fetch-http-error-preserves-retry-reason ()
  (let ((disco-avatar--image-cache (make-hash-table :test #'equal))
        (disco-avatar--fetching (make-hash-table :test #'equal))
        (disco-avatar--failures (make-hash-table :test #'equal))
        (disco-avatar--fetch-generation 7)
        else-callback)
    (cl-letf (((symbol-function 'disco-avatar--ensure-queue)
               (lambda () 'avatar-queue))
              ((symbol-function 'plz-run) #'ignore)
              ((symbol-function 'plz-queue)
               (lambda (_queue _method _url &rest arguments)
                 (setq else-callback (plist-get arguments :else))))
              ((symbol-function 'disco-avatar--schedule-next-retry) #'ignore)
              ((symbol-function 'message) #'ignore))
      (disco-avatar--start-fetch
       "avatar" "https://cdn.invalid/avatar.png" "/tmp/avatar")
      (should (gethash "avatar" disco-avatar--fetching))
      (funcall else-callback '(:status 429 :message "rate limited"))
      (let ((failure (gethash "avatar" disco-avatar--failures)))
        (should-not (gethash "avatar" disco-avatar--fetching))
        (should (= 429 (plist-get failure :status)))
        (should (equal "rate limited" (plist-get failure :reason)))
        (should-not (plist-get failure :permanent))))))

(ert-deftest disco-avatar-image-respects-backoff-and-retries-when-due ()
  (let* ((disco-avatar--image-cache (make-hash-table :test #'equal))
         (disco-avatar--known-keys (make-hash-table :test #'equal))
         (disco-avatar--failures (make-hash-table :test #'equal))
         (disco-avatar--fetching (make-hash-table :test #'equal))
         (disco-avatar-image-size 28)
         (user '((id . "123") (avatar . "hash")))
         (cache-key (disco-avatar-cache-key user))
         started)
    (puthash cache-key
             (list :retry-at (+ (float-time) 60) :permanent nil)
             disco-avatar--failures)
    (cl-letf (((symbol-function 'disco-avatar--rendering-available-p)
               (lambda () t))
              ((symbol-function 'disco-avatar--cached-file-for-key)
               (lambda (_key) nil))
              ((symbol-function 'disco-avatar--start-fetch)
               (lambda (&rest arguments) (setq started arguments))))
      (should-not (disco-avatar-image user))
      (should-not started)
      (puthash cache-key '(:retry-at 0 :permanent nil)
               disco-avatar--failures)
      (should-not (disco-avatar-image user))
      (should (equal cache-key (car started)))
      (should (equal (disco-avatar-url user) (cadr started)))
      (should (equal (disco-avatar--cache-file-base cache-key)
                     (caddr started))))))

(ert-deftest disco-avatar-fetch-is-single-flight-with-queue-owned-concurrency ()
  (let ((disco-avatar--image-cache (make-hash-table :test #'equal))
        (disco-avatar--fetching (make-hash-table :test #'equal))
        (disco-avatar--fetch-generation 1)
        (requests 0))
    (cl-letf (((symbol-function 'disco-avatar--ensure-queue)
               (lambda () 'avatar-queue))
              ((symbol-function 'plz-queue)
               (lambda (&rest _arguments) (cl-incf requests)))
              ((symbol-function 'plz-run) #'ignore))
      (disco-avatar--start-fetch "avatar" "https://cdn.invalid/a" "/tmp/a")
      (disco-avatar--start-fetch "avatar" "https://cdn.invalid/a" "/tmp/a")
      (disco-avatar--start-fetch "other" "https://cdn.invalid/b" "/tmp/b")
      (should (= 2 requests))
      (should (gethash "avatar" disco-avatar--fetching))
      (should (gethash "other" disco-avatar--fetching)))))

(ert-deftest disco-avatar-download-success-writes-cache-and-publishes-resource ()
  (let* ((directory (make-temp-file "disco-avatar-success-" t))
         (cache-base (expand-file-name "avatar" directory))
         (target-file (concat cache-base ".png"))
         (disco-avatar--image-cache (make-hash-table :test #'equal))
         (disco-avatar--fetching (make-hash-table :test #'equal))
         (disco-avatar--failures (make-hash-table :test #'equal))
         (disco-avatar--fetch-generation 9)
         then-callback
         published-key
         retry-rescheduled)
    (unwind-protect
        (cl-letf (((symbol-function 'disco-avatar--ensure-queue)
                   (lambda () 'avatar-queue))
                  ((symbol-function 'plz-queue)
                   (lambda (_queue _method _url &rest arguments)
                     (setq then-callback (plist-get arguments :then))))
                  ((symbol-function 'plz-run) #'ignore)
                  ((symbol-function 'appkit-media-normalize-image-bytes)
                   #'identity)
                  ((symbol-function 'appkit-media-bytes-to-extension)
                   (lambda (_bytes _fallback) "png"))
                  ((symbol-function 'disco-avatar--image-from-file)
                   (lambda (file)
                     (should (equal target-file file))
                     (should (file-exists-p file))
                     :decoded-image))
                  ((symbol-function 'disco-avatar--schedule-next-retry)
                   (lambda () (setq retry-rescheduled t)))
                  ((symbol-function 'disco-avatar--schedule-resource-update)
                   (lambda (cache-key) (setq published-key cache-key))))
          (disco-avatar--start-fetch
           "avatar" "https://cdn.invalid/avatar.png" cache-base)
          (should (functionp then-callback))
          (funcall then-callback "\x89PNG\r\n\x1a\nimage bytes")
          (should (equal "\x89PNG\r\n\x1a\nimage bytes"
                         (with-temp-buffer
                           (set-buffer-multibyte nil)
                           (insert-file-contents-literally target-file)
                           (buffer-string))))
          (should (eq :decoded-image
                      (gethash "avatar" disco-avatar--image-cache)))
          (should-not (gethash "avatar" disco-avatar--fetching))
          (should-not (gethash "avatar" disco-avatar--failures))
          (should retry-rescheduled)
          (should (equal "avatar" published-key)))
      (delete-directory directory t))))

(ert-deftest disco-avatar-resource-hook-coalesces-logical-keys ()
  (let ((disco-avatar--pending-resource-updates
         (make-hash-table :test #'equal))
        (disco-avatar--resource-update-timer nil)
        (disco-avatar-resources-updated-hook nil)
        (scheduled 0)
        received)
    (add-hook 'disco-avatar-resources-updated-hook
              (lambda (resources) (setq received resources)))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (&rest _arguments)
                 (cl-incf scheduled)
                 'avatar-resource-timer))
              ((symbol-function 'timerp)
               (lambda (value) (eq value 'avatar-resource-timer))))
      (disco-avatar--schedule-resource-update "a")
      (disco-avatar--schedule-resource-update "a")
      (disco-avatar--schedule-resource-update "b")
      (should (= 1 scheduled))
      (disco-avatar--flush-resource-updates)
      (should-not disco-avatar--resource-update-timer)
      (should (= 0 (hash-table-count
                    disco-avatar--pending-resource-updates)))
      (should (equal '((:avatar "a") (:avatar "b"))
                     (sort received
                           (lambda (left right)
                             (string< (cadr left) (cadr right)))))))))

(ert-deftest disco-avatar-rounded-image-does-not-bypass-rendering-gate ()
  (let (cache-read)
    (cl-letf (((symbol-function 'disco-avatar-image)
               (lambda (_user) nil))
              ((symbol-function 'disco-avatar-cached-file)
               (lambda (_user) (setq cache-read t) "/tmp/avatar.png")))
      (should-not (disco-avatar-rounded-image '((id . "1")) 16))
      (should-not cache-read))))

(ert-deftest disco-avatar-reset-revokes-callbacks-before-cancel-and-clears-reentry ()
  (let* ((directory (make-temp-file "disco-avatar-reset-" t))
         (cache-base (expand-file-name "avatar" directory))
         (target-file (concat cache-base ".png"))
         (disco-avatar--image-cache (make-hash-table :test #'equal))
         (disco-avatar--rounded-image-cache (make-hash-table :test #'equal))
         (disco-avatar--fetching (make-hash-table :test #'equal))
         (disco-avatar--failures (make-hash-table :test #'equal))
         (disco-avatar--known-keys (make-hash-table :test #'equal))
         (disco-avatar--pending-resource-updates
          (make-hash-table :test #'equal))
         (disco-avatar--fetch-generation 11)
         (disco-avatar--plz-queue nil)
         (disco-avatar--plz-queue-limit nil)
         (disco-avatar--plz-queues nil)
         (disco-avatar--retry-timer 'retry-timer)
         (disco-avatar--resource-update-timer 'resource-timer)
         (disco-avatar-resources-updated-hook nil)
         then-callback
         (requests 0)
         cleared-queues
         canceled-timers
         (hook-count 0))
    (unwind-protect
        (progn
          (add-hook 'disco-avatar-resources-updated-hook
                    (lambda (_resources) (cl-incf hook-count)))
          (cl-letf (((symbol-function 'disco-avatar--ensure-queue)
                     (lambda ()
                       (setq disco-avatar--plz-queue 'avatar-queue
                             disco-avatar--plz-queue-limit 6
                             disco-avatar--plz-queues '(avatar-queue))
                       'avatar-queue))
                    ((symbol-function 'plz-queue)
                     (lambda (_queue _method _url &rest arguments)
                       (cl-incf requests)
                       (setq then-callback (plist-get arguments :then))))
                    ((symbol-function 'plz-run) #'ignore)
                    ((symbol-function 'timerp)
                     (lambda (value)
                       (memq value '(retry-timer resource-timer))))
                    ((symbol-function 'cancel-timer)
                     (lambda (timer)
                       (push timer canceled-timers)
                       (puthash "resurrected" t disco-avatar--failures)))
                    ((symbol-function 'plz-clear)
                     (lambda (queue)
                       (push queue cleared-queues)
                       ;; Cancellation is allowed to invoke callbacks
                       ;; synchronously.  Authority is already revoked.
                       (funcall then-callback "late image bytes")
                       (disco-avatar--start-fetch
                        "successor" "https://cdn.invalid/new" cache-base)
                       (puthash "resurrected" t disco-avatar--image-cache)))
                    ((symbol-function 'disco-avatar--image-from-file)
                     (lambda (_file) :late-image)))
            (disco-avatar--start-fetch
             "avatar" "https://cdn.invalid/avatar.png" cache-base)
            (should (= 1 requests))
            (puthash "avatar" t disco-avatar--known-keys)
            (puthash '(:avatar "avatar") t
                     disco-avatar--pending-resource-updates)
            (disco-avatar-reset-session-state))
          (should (= 12 disco-avatar--fetch-generation))
          (should (= 1 requests))
          (should (equal '(avatar-queue) cleared-queues))
          (should (equal '(resource-timer retry-timer) canceled-timers))
          (dolist (table (list disco-avatar--image-cache
                               disco-avatar--rounded-image-cache
                               disco-avatar--fetching
                               disco-avatar--failures
                               disco-avatar--known-keys
                               disco-avatar--pending-resource-updates))
            (should (= 0 (hash-table-count table))))
          (should-not disco-avatar--plz-queue)
          (should-not disco-avatar--plz-queues)
          (should-not disco-avatar--retry-timer)
          (should-not disco-avatar--resource-update-timer)
          (should-not (file-exists-p target-file))
          (should (= 0 hook-count)))
      (delete-directory directory t))))

(provide 'disco-avatar-test)

;;; disco-avatar-test.el ends here
