;;; disco-room-test.el --- Tests for disco-room pin ack flow -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(add-to-list 'load-path
             (expand-file-name ".."
                               (file-name-directory (or load-file-name buffer-file-name))))

(require 'disco-room)
(require 'disco-state)

(ert-deftest disco-room-ack-channel-pins-applies-state-on-success ()
  (with-temp-buffer
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "chan")
       (type . 0)
       (last_pin_timestamp . "2026-03-04T01:00:00.000000+00:00")))
    (let ((disco-room--channel-id "chan")
          (disco-room--refresh-generation 1)
          called-channel-id)
      (cl-letf (((symbol-function 'disco-api-ack-channel-pins-async)
                 (lambda (channel-id &rest args)
                   (setq called-channel-id channel-id)
                   (funcall (plist-get args :on-success) nil)))
                ((symbol-function 'disco-room--callback-active-p)
                 (lambda (&rest _args) t))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (disco-room-ack-channel-pins)
        (should (equal "chan" called-channel-id))
        (should (equal "2026-03-04T01:00:00.000000+00:00"
                       (disco-state-channel-last-read-pin-timestamp "chan")))))))

(ert-deftest disco-room-ack-channel-pins-skips-when-already-acked ()
  (with-temp-buffer
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "chan")
       (type . 0)
       (last_pin_timestamp . "2026-03-04T01:00:00.000000+00:00")))
    (disco-state-apply-channel-pins-ack
     "chan"
     "2026-03-04T01:00:00.000000+00:00")
    (let ((disco-room--channel-id "chan")
          (api-called nil))
      (cl-letf (((symbol-function 'disco-api-ack-channel-pins-async)
                 (lambda (&rest _args)
                   (setq api-called t)))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (disco-room-ack-channel-pins)
        (should-not api-called)))))

(ert-deftest disco-room-handle-gateway-pin-events-refresh-current-frame ()
  (with-temp-buffer
    (let ((disco-room--channel-id "chan")
          (disco-room--channel-name "old")
          (frame-called nil))
      (cl-letf (((symbol-function 'disco-room--channel-object)
                 (lambda () '((id . "chan") (name . "new"))))
                ((symbol-function 'disco-room--update-frame-preserving-point)
                 (lambda () (setq frame-called t))))
        (disco-room--handle-gateway-event
         '(:type channel-pins-update
           :channel-id "chan"))
        (should frame-called)
        (should (equal "new" disco-room--channel-name))))))

(ert-deftest disco-room-resolve-pending-jump-fetches-around-once ()
  (with-temp-buffer
    (let ((disco-room--pending-jump-message-id "m1")
          fetched)
      (cl-letf (((symbol-function 'disco-room--jump-to-visible-message)
                 (lambda (_message-id) nil))
                ((symbol-function 'disco-room--fetch-around-pending-jump)
                 (lambda ()
                   (setq fetched t))))
        (disco-room--resolve-pending-jump)
        (should fetched)))))

(ert-deftest disco-room-search-channel-opens-root-search-transient ()
  (with-temp-buffer
    (disco-room-mode)
    (let ((disco-room--channel-id "c1")
          passed-channel)
      (disco-state-reset)
      (disco-state-upsert-channel '((id . "c1") (type . 1) (name . "dm")))
      (cl-letf (((symbol-function 'disco-root-search-channel-transient)
                 (lambda (channel)
                   (setq passed-channel channel))))
        (disco-room-search-channel)
        (should (equal "c1" (alist-get 'id passed-channel)))))))

(ert-deftest disco-room-fetch-around-pending-jump-replaces-cache-and-jumps ()
  (with-temp-buffer
    (disco-room-mode)
    (let ((disco-room--channel-id "chan")
          (disco-room--pending-jump-message-id "m2")
          (disco-room--refresh-generation 0)
          jumped
          rendered)
      (disco-state-reset)
      (disco-state-put-messages
       "chan"
       '(((id . "m9") (channel_id . "chan") (content . "newer"))))
      (cl-letf (((symbol-function 'disco-api-channel-messages-around-async)
                 (lambda (_channel-id _message-id &rest args)
                   (funcall (plist-get args :on-success)
                            '(((id . "m3") (channel_id . "chan") (content . "older"))
                              ((id . "m2") (channel_id . "chan") (content . "target"))
                              ((id . "m1") (channel_id . "chan") (content . "oldest"))))))
                ((symbol-function 'disco-room--callback-active-p)
                 (lambda (&rest _args) t))
                ((symbol-function 'disco-room-render)
                 (lambda ()
                   (setq rendered t)))
                ((symbol-function 'disco-room--jump-to-visible-message)
                 (lambda (message-id)
                   (setq jumped message-id)
                   t))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (disco-room--fetch-around-pending-jump)
        (should rendered)
        (should (equal "m2" jumped))
        (should-not disco-room--pending-jump-message-id)
        (should (equal '("m3" "m2" "m1")
                       (mapcar (lambda (msg) (alist-get 'id msg))
                               (disco-state-messages "chan"))))))))

(ert-deftest disco-room-fetch-around-pending-jump-errors-when-target-missing ()
  (with-temp-buffer
    (disco-room-mode)
    (let ((disco-room--channel-id "chan")
          (disco-room--pending-jump-message-id "m2")
          (disco-room--refresh-generation 0)
          rendered)
      (disco-state-reset)
      (cl-letf (((symbol-function 'disco-api-channel-messages-around-async)
                 (lambda (_channel-id _message-id &rest args)
                   (funcall (plist-get args :on-success)
                            '(((id . "m3") (channel_id . "chan") (content . "older"))))))
                ((symbol-function 'disco-room--callback-active-p)
                 (lambda (&rest _args) t))
                ((symbol-function 'disco-room-render)
                 (lambda ()
                   (setq rendered t)))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (disco-room--fetch-around-pending-jump)
        (should-not rendered)
        (should-not disco-room--pending-jump-message-id)
        (should-not (disco-state-messages "chan"))))))

(ert-deftest disco-room-filter-search-activates-msg-filter ()
  (with-temp-buffer
    (disco-room-mode)
    (let ((disco-room--channel-id "chan")
          rendered)
      (cl-letf (((symbol-function 'disco-room--search-current-channel-async)
                 (lambda (&rest args)
                   (funcall (plist-get args :on-success)
                            '((total_results . 1)
                              (messages (((id . "m1")
                                          (channel_id . "chan")
                                          (content . "hello"))))))))
                ((symbol-function 'disco-room--render-preserving-point)
                 (lambda () (setq rendered t)))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (disco-room-filter-search "hello")
        (should rendered)
        (should (equal "hello" (plist-get disco-room--msg-filter :query)))
        (should (equal '("m1")
                       (mapcar (lambda (msg) (alist-get 'id msg))
                               (plist-get disco-room--msg-filter :items))))))))

(ert-deftest disco-room-filter-search-rejects-unsupported-channel-types ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "voice")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "voice") (type . 2) (name . "Voice")))
    (should-error (disco-room-filter-search "hello") :type 'error)))

(ert-deftest disco-room-filter-search-supports-ephemeral-dm ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "ephemeral")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "ephemeral") (type . 18)))
    (should (disco-room--searchable-channel-type-p))
    (should (equal "ephemeral-dm"
                   (disco-room--searchable-channel-type-name)))))

(ert-deftest disco-room-search-current-channel-auto-includes-age-restricted-thread ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "thread")
    (setq-local disco-room--guild-id "g1")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "parent")
       (type . 0)
       (guild_id . "g1")
       (nsfw . t)))
    (disco-state-upsert-channel
     '((id . "thread")
       (type . 11)
       (guild_id . "g1")
       (parent_id . "parent")))
    (let (captured)
      (cl-letf (((symbol-function 'disco-api-guild-search-messages-async)
                 (lambda (guild-id &rest args)
                   (setq captured (cons guild-id args)))))
        (disco-room--search-current-channel-async :query "hello")
        (should (equal "g1" (car captured)))
        (should (eq t (plist-get (cdr captured) :include-nsfw)))))))

(ert-deftest disco-room-composer-visible-p-hides-read-only-guild-channel ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "readonly")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "readonly")
       (type . 0)
       (guild_id . "g1")
       (permissions . "0")))
    (should-not (disco-room--composer-visible-p))
    (should (equal '(send-messages)
                   (disco-room--composer-missing-permissions)))))

(ert-deftest disco-room-composer-visible-p-uses-thread-send-permission ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "thread")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "thread")
       (type . 11)
       (guild_id . "g1")
       (permissions . "2048")))
    (should-not (disco-room--composer-visible-p))
    (should (equal '(send-messages-in-threads)
                   (disco-room--composer-missing-permissions)))))

(ert-deftest disco-room-composer-visible-p-hides-system-user-dm ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "sysdm")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "sysdm")
       (type . 1)
       (recipients . (((id . "643945264868098049")
                       (username . "Discord")
                       (system . t))))))
    (should-not (disco-room--composer-visible-p))
    (should (string-match-p "official Discord system DMs are read-only"
                            (disco-room--composer-hidden-status-line)))))

(ert-deftest disco-room-render-hides-composer-when-send-permission-missing ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "readonly")
    (setq-local disco-room--channel-name "readonly")
    (setq-local disco-room--draft-input "hello")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "readonly")
       (type . 0)
       (guild_id . "g1")
       (permissions . "0")))
    (disco-room-render)
    (should-not (text-property-any (point-min) (point-max) 'disco-room-input t))
    (should-not (marker-buffer disco-room--input-marker))
    (should (string-match-p "composer hidden: missing SEND_MESSAGES"
                            (buffer-string)))
    (should-not (string-match-p "type at >>>" (buffer-string)))))

(ert-deftest disco-room-render-shows-age-restricted-header-tag ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "adult")
    (setq-local disco-room--channel-name "adult")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "adult")
       (type . 0)
       (guild_id . "g1")
       (permissions . "2048")
       (nsfw . t)))
    (disco-room-render)
    (should (string-match-p (regexp-quote "Channel: adult [18+]")
                            (buffer-string)))))

(ert-deftest disco-room-render-shows-reply-and-attachments-near-composer ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (setq-local disco-room--channel-name "chat")
    (setq-local disco-room--draft-input "hello")
    (setq-local disco-room--pending-reply-to "m42")
    (setq-local disco-room--pending-attachments
                '((:token-id 1 :path "/tmp/a.txt")
                  (:token-id 2 :path "/tmp/b.png" :description "preview")))
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "chat")
       (type . 0)
       (guild_id . "g1")
       (permissions . "2048")))
    (disco-state-put-messages
     "chat"
     '(((id . "m42")
        (channel_id . "chat")
        (content . "hello reply")
        (author . ((id . "u1") (username . "alice"))))))
    (disco-room-render)
    (should (text-property-any (point-min) (point-max) 'disco-room-input t))
    (should (string-match-p "Replying to alice \\[m42\\]"
                            (buffer-string)))
    (should (string-match-p "> hello reply"
                            (buffer-string)))
    (should (string-match-p "Queued attachments: \\\[file:1\\\] a.txt, \\\[file:2\\\] b.png - preview"
                            (buffer-string)))))

(ert-deftest disco-room-render-keeps-reply-context-when-composer-hidden ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "readonly")
    (setq-local disco-room--channel-name "readonly")
    (setq-local disco-room--pending-reply-to "m42")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "readonly")
       (type . 0)
       (guild_id . "g1")
       (permissions . "0")))
    (disco-state-put-messages
     "readonly"
     '(((id . "m42")
        (channel_id . "readonly")
        (content . "hello reply")
        (author . ((id . "u1") (username . "alice"))))))
    (disco-room-render)
    (should-not (text-property-any (point-min) (point-max) 'disco-room-input t))
    (should (string-match-p "Replying to alice \\[m42\\]"
                            (buffer-string)))))

(ert-deftest disco-room-edit-message-enters-composer-edit-mode ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (setq-local disco-room--channel-name "chat")
    (setq-local disco-room--draft-input "saved draft")
    (let ((msg '((id . "m1")
                 (channel_id . "chat")
                 (content . "old body")
                 (author . ((id . "u1") (username . "alice"))))))
      (disco-state-reset)
      (disco-state-upsert-channel
       '((id . "chat")
         (type . 0)
         (guild_id . "g1")
         (permissions . "2048")))
      (disco-state-put-messages "chat" (list msg))
      (cl-letf (((symbol-function 'disco-room--message-at-point)
                 (lambda () msg))
                ((symbol-function 'disco-gateway-current-user-id)
                 (lambda () "u1"))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (disco-room-edit-message))
      (should (disco-room--composer-edit-active-p))
      (should (equal "m1" (disco-room--composer-edit-message-id)))
      (should (equal "old body" disco-room--draft-input))
      (should (string-match-p "Editing alice \\[m1\\]"
                              (buffer-string)))
      (should (string-match-p "> old body"
                              (buffer-string)))
      (should (string-match-p "RET/C-c C-c: save edit"
                              (buffer-string))))))

(ert-deftest disco-room-send-message-commits-composer-edit-and-restores-state ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (setq-local disco-room--channel-name "chat")
    (let ((msg '((id . "m1")
                 (channel_id . "chat")
                 (content . "old body")
                 (author . ((id . "u1") (username . "alice"))))))
      (disco-state-reset)
      (disco-state-upsert-channel
       '((id . "chat")
         (type . 0)
         (guild_id . "g1")
         (permissions . "2048")))
      (disco-state-put-messages "chat" (list msg))
      (setq-local disco-room--draft-input "saved draft [file:1]")
      (puthash "1" '(:token-id "1" :path "/tmp/a.txt") disco-room--attachment-token-table)
      (setq-local disco-room--attachment-token-seq 1)
      (disco-room--sync-pending-attachments-from-draft)
      (cl-letf (((symbol-function 'disco-room--message-at-point)
                 (lambda () msg))
                ((symbol-function 'disco-gateway-current-user-id)
                 (lambda () "u1"))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (disco-room-edit-message))
      (disco-room--set-draft "updated body")
      (let (edit-call refresh-called send-called)
        (cl-letf (((symbol-function 'disco-api-edit-message-async)
                   (lambda (channel-id message-id content &rest args)
                     (setq edit-call (list channel-id message-id content))
                     (funcall (plist-get args :on-success) nil)))
                  ((symbol-function 'disco-gateway-current-user-id)
                   (lambda () "u1"))
                  ((symbol-function 'disco-api-send-message-async)
                   (lambda (&rest _args)
                     (setq send-called t)))
                  ((symbol-function 'disco-room-refresh)
                   (lambda ()
                     (setq refresh-called t)))
                  ((symbol-function 'disco-room--channel-buffer-p)
                   (lambda (&rest _args) t))
                  ((symbol-function 'message)
                   (lambda (&rest _args) nil)))
          (disco-room-send-message))
        (should (equal '("chat" "m1" "updated body") edit-call))
        (should refresh-called)
        (should-not send-called)
        (should-not (disco-room--composer-edit-active-p))
        (should (equal "saved draft [file:1]" disco-room--draft-input))
        (should-not disco-room--pending-reply-to)
        (should (equal '("1")
                       (disco-room--attachment-token-ids-in-text
                        disco-room--draft-input)))
        (should (= 1 (hash-table-count disco-room--attachment-token-table)))))))

(ert-deftest disco-room-render-shows-composer-when-send-permission-present ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (setq-local disco-room--channel-name "chat")
    (setq-local disco-room--draft-input "hello")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "chat")
       (type . 0)
       (guild_id . "g1")
       (permissions . "2048")))
    (disco-room-render)
    (should (text-property-any (point-min) (point-max) 'disco-room-input t))
    (should (markerp disco-room--input-marker))
    (should (string-match-p "type at >>>" (buffer-string)))))

(ert-deftest disco-room-set-draft-preserves-ewoc-and-input-markers ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (setq-local disco-room--channel-name "chat")
    (setq-local disco-room--draft-input "hello")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "chat")
       (type . 0)
       (guild_id . "g1")
       (permissions . "2048")))
    (disco-room-render)
    (let ((ewoc disco-room--ewoc)
          (input-marker disco-room--input-marker)
          (prompt-marker disco-room--input-prompt-marker))
      (disco-room--set-draft "updated body")
      (should (eq ewoc disco-room--ewoc))
      (should (eq input-marker disco-room--input-marker))
      (should (eq prompt-marker disco-room--input-prompt-marker))
      (should (string-match-p "> updated body" (buffer-string))))))

(ert-deftest disco-room-render-reuses-existing-message-nodes ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (setq-local disco-room--channel-name "chat")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "chat")
       (type . 0)
       (guild_id . "g1")
       (permissions . "2048")))
    (disco-state-put-messages
     "chat"
     '(((id . "m2") (channel_id . "chat") (content . "two"))
       ((id . "m1") (channel_id . "chat") (content . "one"))))
    (disco-room-render)
    (let ((ewoc disco-room--ewoc)
          (node-m1 (gethash "m1" disco-room--message-node-table))
          (node-m2 (gethash "m2" disco-room--message-node-table)))
      (disco-state-put-messages
       "chat"
       '(((id . "m3") (channel_id . "chat") (content . "three"))
         ((id . "m2") (channel_id . "chat") (content . "two updated"))
         ((id . "m1") (channel_id . "chat") (content . "one"))))
      (disco-room-render)
      (should (eq ewoc disco-room--ewoc))
      (should (eq node-m1 (gethash "m1" disco-room--message-node-table)))
      (should (eq node-m2 (gethash "m2" disco-room--message-node-table)))
      (should (gethash "m3" disco-room--message-node-table))
      (should (equal '("m1" "m2" "m3")
                     disco-room--displayed-message-ids))
      (should (string-match-p "two updated" (buffer-string))))))

(ert-deftest disco-room-composer-visible-p-hides-archived-thread ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "thread")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "thread")
       (type . 11)
       (guild_id . "g1")
       (permissions . "274877906944")
       (thread_metadata . ((archived . t)))))
    (should-not (disco-room--composer-visible-p))
    (should (string-match-p "current thread is archived"
                            (disco-room--composer-hidden-status-line)))))

(ert-deftest disco-room-attach-file-errors-while-editing ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "chat") (type . 0) (guild_id . "g1") (permissions . "2048")))
    (setq-local disco-room--pending-edit '(:type edit :message-id "m1" :saved-state nil))
    (let ((path (make-temp-file "disco-room-attach")))
      (unwind-protect
          (should-error (disco-room-attach-file path) :type 'user-error)
        (delete-file path)))))

(ert-deftest disco-room-remove-attachment-token-errors-while-editing ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--pending-edit '(:type edit :message-id "m1" :saved-state nil))
    (setq-local disco-room--draft-input "[file:1]")
    (should-error (disco-room-remove-attachment-token-at-point) :type 'user-error)))

(ert-deftest disco-room-delete-message-errors-without-manage-messages ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (let ((msg '((id . "m2")
                 (channel_id . "chat")
                 (content . "body")
                 (author . ((id . "u2") (username . "bob"))))))
      (disco-state-reset)
      (disco-state-upsert-channel '((id . "chat") (type . 0) (guild_id . "g1") (permissions . "2048")))
      (cl-letf (((symbol-function 'disco-room--message-at-point)
                 (lambda () msg))
                ((symbol-function 'disco-gateway-current-user-id)
                 (lambda () "u1")))
        (should-error (disco-room-delete-message) :type 'user-error)))))

(ert-deftest disco-room-create-thread-from-message-errors-without-create-public-threads ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "chat") (type . 0) (guild_id . "g1") (permissions . "2048")))
    (should-error (disco-room-create-thread-from-message "topic" "m1") :type 'user-error)))

(ert-deftest disco-room-create-thread-errors-without-create-private-threads ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (disco-state-reset)
    (disco-state-upsert-channel
     `((id . "chat")
       (type . 0)
       (guild_id . "g1")
       (permissions . ,(number-to-string (ash 1 35)))))
    (should-error (disco-room-create-thread "topic" 12 nil nil nil) :type 'user-error)))

(ert-deftest disco-room-add-reaction-errors-without-add-reactions ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "chat") (type . 0) (guild_id . "g1") (permissions . "2048")))
    (should-error (disco-room-add-reaction "👍" "m1") :type 'user-error)))

(ert-deftest disco-room-vote-poll-answer-errors-in-archived-thread ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "thread")
    (let* ((poll-msg
            '((id . "m1")
              (channel_id . "thread")
              (poll . ((answers . (((answer_id . 1)
                                    (poll_media . ((text . "one"))))
                                   ((answer_id . 2)
                                    (poll_media . ((text . "two")))))))))))
      (disco-state-reset)
      (disco-state-upsert-channel
       `((id . "thread")
         (type . 11)
         (guild_id . "g1")
         (permissions . ,(number-to-string (ash 1 38)))
         (thread_metadata . ((archived . t)))))
      (disco-state-put-messages "thread" (list poll-msg))
      (should-error (disco-room-vote-poll-answer 1 "m1") :type 'user-error))))

(ert-deftest disco-room-rename-thread-errors-when-archived ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "thread")
    (disco-state-reset)
    (disco-state-upsert-channel
     `((id . "thread")
       (type . 11)
       (guild_id . "g1")
       (permissions . ,(number-to-string (ash 1 34)))
       (thread_metadata . ((archived . t)))))
    (should-error (disco-room-rename-thread "new-name") :type 'user-error)))

(ert-deftest disco-room-toggle-thread-archived-errors-without-manage-threads ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "thread")
    (disco-state-reset)
    (disco-state-upsert-channel
     `((id . "thread")
       (type . 11)
       (guild_id . "g1")
       (permissions . ,(number-to-string (ash 1 38)))
       (thread_metadata . ((archived . :false) (locked . :false)))))
    (should-error (disco-room-toggle-thread-archived) :type 'user-error)))

(ert-deftest disco-room-join-thread-errors-when-already-joined ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "thread")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "thread") (type . 11) (guild_id . "g1")
                                  (thread_metadata . ((archived . :false)))))
    (disco-state-upsert-thread-member "thread" "u1")
    (cl-letf (((symbol-function 'disco-gateway-current-user-id)
               (lambda () "u1")))
      (should-error (disco-room-join-thread) :type 'user-error))))

(ert-deftest disco-room-leave-thread-errors-when-not-joined ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "thread")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "thread") (type . 11) (guild_id . "g1")
                                  (thread_metadata . ((archived . :false)))))
    (cl-letf (((symbol-function 'disco-gateway-current-user-id)
               (lambda () "u1")))
      (should-error (disco-room-leave-thread) :type 'user-error))))

(ert-deftest disco-room-set-thread-muted-errors-when-not-joined ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "thread")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "thread") (type . 11) (guild_id . "g1")
                                  (thread_metadata . ((archived . :false)))))
    (cl-letf (((symbol-function 'disco-gateway-current-user-id)
               (lambda () "u1")))
      (should-error (disco-room-set-thread-muted t) :type 'user-error))))

(ert-deftest disco-room-send-poll-errors-while-replying ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (setq-local disco-room--pending-reply-to "m1")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "chat") (type . 0) (guild_id . "g1") (permissions . "562949953423360")))
    (should-error (disco-room-send-poll "Q" '("a" "b") 24 nil nil)
                  :type 'user-error)))

(ert-deftest disco-room-forward-message-errors-while-replying ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (setq-local disco-room--pending-reply-to "m1")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "chat") (type . 0) (guild_id . "g1") (permissions . "2048")))
    (should-error (disco-room-forward-message "m2" "src" nil nil)
                  :type 'user-error)))

(ert-deftest disco-room-send-message-errors-for-system-user-dm ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "sysdm")
    (setq-local disco-room--draft-input "hello")
    (disco-state-reset)
    (disco-state-upsert-channel
     '((id . "sysdm")
       (type . 1)
       (recipients . (((id . "643945264868098049")
                       (username . "Discord")
                       (system . t))))))
    (should-error (disco-room-send-message) :type 'user-error)))

(ert-deftest disco-room-edit-message-errors-while-replying ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chat")
    (setq-local disco-room--pending-reply-to "m1")
    (let ((msg '((id . "m2")
                 (channel_id . "chat")
                 (content . "body")
                 (author . ((id . "u1") (username . "alice"))))))
      (disco-state-reset)
      (disco-state-upsert-channel '((id . "chat") (type . 0) (guild_id . "g1") (permissions . "2048")))
      (cl-letf (((symbol-function 'disco-room--message-at-point)
                 (lambda () msg)))
        (should-error (disco-room-edit-message) :type 'user-error)))))

(ert-deftest disco-room-refresh-reruns-active-filter ()
  (with-temp-buffer
    (disco-room-mode)
    (let ((disco-room--msg-filter '(:active t :query "hello"))
          refreshed)
      (cl-letf (((symbol-function 'disco-room-filter-refresh)
                 (lambda () (setq refreshed t))))
        (disco-room-refresh)
        (should refreshed)))))

(ert-deftest disco-room-load-older-messages-loads-more-filter-results ()
  (with-temp-buffer
    (disco-room-mode)
    (let ((disco-room--msg-filter '(:active t :query "hello"))
          loaded-more)
      (cl-letf (((symbol-function 'disco-room-filter-load-more)
                 (lambda () (setq loaded-more t))))
        (disco-room-load-older-messages)
        (should loaded-more)))))

(ert-deftest disco-room-highlight-search-query-adds-face ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--inplace-search-filter '(:query "beta"))
    (let* ((text (disco-room--highlight-search-query "alpha beta gamma"))
           (start (string-match "beta" text)))
      (should (integerp start))
      (should (eq 'disco-room-search-highlight
                  (get-text-property start 'face text))))))

(ert-deftest disco-room-inplace-search-dispatch-local-hit-skips-api ()
  (with-temp-buffer
    (disco-room-mode)
    (let ((disco-room--channel-id "chan")
          api-called)
      (disco-state-reset)
      (disco-state-put-messages "chan"
                                '(((id . "m2") (channel_id . "chan") (content . "beta"))
                                  ((id . "m1") (channel_id . "chan") (content . "alpha"))))
      (let ((inhibit-read-only t))
        (insert "alpha\n")
        (add-text-properties (line-beginning-position 0) (line-end-position 0)
                             '(disco-message-id "m1"))
        (insert "beta\n")
        (add-text-properties (line-beginning-position 0) (line-end-position 0)
                             '(disco-message-id "m2")))
      (goto-char (point-min))
      (cl-letf (((symbol-function 'disco-room--search-current-channel-async)
                 (lambda (&rest _args)
                   (setq api-called t)))
                ((symbol-function 'disco-room--render-preserving-point)
                 (lambda () nil)))
        (disco-room--inplace-search-dispatch '(:query "beta") t)
        (should-not api-called)
        (should (equal "m2" (get-text-property (line-beginning-position) 'disco-message-id)))))))

(ert-deftest disco-room-inplace-search-dispatch-rerenders-when-highlight-query-changes ()
  (with-temp-buffer
    (disco-room-mode)
    (let ((disco-room--channel-id "chan")
          rendered)
      (disco-state-reset)
      (disco-state-put-messages "chan"
                                '(((id . "m1") (channel_id . "chan") (content . "alpha"))))
      (let ((inhibit-read-only t))
        (insert "alpha\n")
        (add-text-properties (point-min) (point-max) '(disco-message-id "m1")))
      (goto-char (point-min))
      (cl-letf (((symbol-function 'disco-room--render-preserving-point)
                 (lambda () (setq rendered t))))
        (disco-room--inplace-search-dispatch '(:query "alpha") t)
        (should rendered)))))

(ert-deftest disco-room-inplace-search-dispatch-server-hit-jumps-to-message ()
  (with-temp-buffer
    (disco-room-mode)
    (let ((disco-room--channel-id "chan")
          jumped)
      (disco-state-reset)
      (setq-local disco-room--newest-message-id "m9")
      (cl-letf (((symbol-function 'disco-room--search-current-channel-async)
                 (lambda (&rest args)
                   (funcall (plist-get args :on-success)
                            '((messages (((id . "m5")
                                          (channel_id . "chan")
                                          (content . "match"))))))))
                ((symbol-function 'disco-room-jump-to-message)
                 (lambda (message-id &optional channel-id)
                   (setq jumped (list message-id channel-id))))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (disco-room--inplace-search-dispatch '(:query "match") nil "m9")
        (should (equal '("m5" "chan") jumped))))))

(ert-deftest disco-room-inplace-search-unsupported-channel-skips-remote-fallback ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "voice")
    (setq-local disco-room--newest-message-id "m9")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "voice") (type . 2) (name . "Voice")))
    (let (api-called)
      (cl-letf (((symbol-function 'disco-room--search-current-channel-async)
                 (lambda (&rest _args)
                   (setq api-called t)))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (should-not (disco-room--inplace-search-dispatch '(:query "match") nil "m9"))
        (should-not api-called)))))

(ert-deftest disco-room-toggle-message-spoilers-switches-active-message ()
  (with-temp-buffer
    (let ((disco-room--revealed-spoiler-message-id nil)
          invalidated)
      (cl-letf (((symbol-function 'disco-room--invalidate-message-node)
                 (lambda (message-id)
                   (push message-id invalidated)
                   t)))
        (disco-room-toggle-message-spoilers "m1")
        (should (equal "m1" disco-room--revealed-spoiler-message-id))
        (should (equal '("m1") invalidated))
        (setq invalidated nil)
        (disco-room-toggle-message-spoilers "m2")
        (should (equal "m2" disco-room--revealed-spoiler-message-id))
        (should (equal '("m2" "m1") invalidated))
        (setq invalidated nil)
        (disco-room-toggle-message-spoilers "m2")
        (should-not disco-room--revealed-spoiler-message-id)
        (should (equal '("m2") invalidated))))))

(ert-deftest disco-room-send-message-splits-overlong-content-by-default ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chan")
    (setq-local disco-room--draft-input "first line\nsecond line\nthird line")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "chan") (type . 0) (permissions . "2048")))
    (let ((disco-api--message-content-limit 12)
          sent
          refreshed)
      (cl-letf (((symbol-function 'disco-room--channel-object)
                 (lambda () '((id . "chan"))))
                ((symbol-function 'disco-room--channel-buffer-p)
                 (lambda (&rest _args) t))
                ((symbol-function 'disco-permission-ensure-channel)
                 (lambda (&rest _args) t))
                ((symbol-function 'disco-room-render)
                 (lambda () nil))
                ((symbol-function 'disco-room-refresh)
                 (lambda () (setq refreshed t)))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil))
                ((symbol-function 'disco-api-send-message-async)
                 (lambda (_channel-id content &rest args)
                   (push content sent)
                   (funcall (plist-get args :on-success) nil))))
        (disco-room-send-message)
        (should (equal '("first line" "second line" "third line")
                       (nreverse sent)))
        (should refreshed)
        (should-not disco-room--send-in-flight)
        (should (equal "" disco-room--draft-input))))))

(ert-deftest disco-room-send-message-sends-overlong-content-as-file-when-configured ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chan")
    (let* ((long-text (make-string 32 ?x))
           (disco-api--message-content-limit 10)
           (disco-room-long-message-action 'file)
           sent-content
           sent-attachments
           captured-file-body)
      (setq-local disco-room--draft-input long-text)
      (disco-state-reset)
      (disco-state-upsert-channel '((id . "chan") (type . 0) (permissions . "2048")))
      (cl-letf (((symbol-function 'disco-room--channel-object)
                 (lambda () '((id . "chan"))))
                ((symbol-function 'disco-room--channel-buffer-p)
                 (lambda (&rest _args) t))
                ((symbol-function 'disco-permission-ensure-channel)
                 (lambda (&rest _args) t))
                ((symbol-function 'disco-room-render)
                 (lambda () nil))
                ((symbol-function 'disco-room-refresh)
                 (lambda () nil))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil))
                ((symbol-function 'disco-api-send-message-with-attachments-async)
                 (lambda (_channel-id &rest args)
                   (setq sent-content (plist-get args :content)
                         sent-attachments (plist-get args :attachments))
                   (with-temp-buffer
                     (insert-file-contents (plist-get (car sent-attachments) :path))
                     (setq captured-file-body (buffer-string)))
                   (funcall (plist-get args :on-success) nil))))
        (disco-room-send-message)
        (should-not sent-content)
        (should (= 1 (length sent-attachments)))
        (should (equal disco-room-long-message-file-name
                       (plist-get (car sent-attachments) :filename)))
        (should (equal long-text captured-file-body))
        (should-not disco-room--send-in-flight)
        (should (equal "" disco-room--draft-input))))))

(ert-deftest disco-room-send-message-rejects-overlong-content-before-send-state ()
  (let ((disco-room-long-message-action 'file))
    (with-temp-buffer
      (disco-room-mode)
      (setq-local disco-room--channel-id "chan")
      (setq-local disco-room--draft-input
                  (make-string (1+ disco-api--message-content-limit) ?a))
      (disco-state-reset)
      (disco-state-upsert-channel '((id . "chan") (type . 0) (permissions . "0")))
      (should-error (disco-room-send-message) :type 'error)
      (should-not disco-room--send-in-flight)
      (should (= (1+ disco-api--message-content-limit)
                 (length disco-room--draft-input))))))

(ert-deftest disco-room-send-poll-rejects-overlong-content-before-send-state ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chan")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "chan") (type . 0) (permissions . "562949953423360")))
    (should-error
     (disco-room-send-poll "Question" '("one" "two") 24 nil
                           (make-string (1+ disco-api--message-content-limit) ?a))
     :type 'error)
    (should-not disco-room--send-in-flight)))

(ert-deftest disco-room-forward-message-rejects-overlong-comment-before-send-state ()
  (with-temp-buffer
    (disco-room-mode)
    (setq-local disco-room--channel-id "chan")
    (disco-state-reset)
    (disco-state-upsert-channel '((id . "chan") (type . 0) (permissions . "2048")))
    (cl-letf (((symbol-function 'disco-room--ensure-jump-permissions)
               (lambda (&rest _args) t)))
      (should-error
       (disco-room-forward-message
        "m1" "chan"
        (make-string (1+ disco-api--message-content-limit) ?a)
        nil)
       :type 'error)
      (should-not disco-room--send-in-flight))))

(ert-deftest disco-room-forward-snapshot-content-uses-internal-markdown-renderer ()
  (let* ((disco-markdown-backend 'internal)
         (msg '((id . "m1")
                (message_snapshots
                 . (((message
                      . ((content . "[link](https://example.com)\n> quote"))))))))
         (rendered (disco-room--forward-snapshot-content msg))
         (plain (substring-no-properties rendered))
         (link-pos (string-match "link" plain))
         (quote-pos (string-match "quote" plain)))
    (should (equal "link\nquote" plain))
    (should (equal "https://example.com"
                   (get-text-property link-pos 'disco-markdown-url rendered)))
    (should (equal "| "
                   (substring-no-properties
                    (get-text-property quote-pos 'line-prefix rendered))))))

(provide 'disco-room-test)

;;; disco-room-test.el ends here
