;;; disco-notifications-test.el --- Tests for desktop notifications -*- lexical-binding: t; -*-

(require 'ert)
(require 'disco-notifications)

(defmacro disco-notifications-test--with-app (&rest body)
  "Evaluate BODY with one isolated live Disco Appkit session."
  (declare (indent 0) (debug t))
  `(let* ((app (appkit-start-app 'disco :id (make-symbol "notification-test")))
          (disco-runtime--app app))
     (unwind-protect
         (progn ,@body)
       (when (appkit-app-live-p app)
         (appkit-stop-app app)))))

(defun disco-notifications-test--message (&optional mention)
  "Return incoming test message, with direct MENTION when non-nil."
  `((id . "100") (channel_id . "c") (content . "hello")
    (author (id . "other") (username . "Alice"))
    (mentions . ,(if mention '(((id . "me"))) nil))
    (mention_everyone . nil) (mention_roles . nil)))

(ert-deftest disco-notifications-policy-honors-level-mute-and-ping ()
  (let ((channel '((id . "c") (type . 0)))
        (level 0)
        muted)
    (cl-letf (((symbol-function 'disco-state-channel)
               (lambda (_id) channel))
              ((symbol-function 'disco-gateway-current-user-id)
               (lambda () "me"))
              ((symbol-function 'disco-state-channel-muted-p)
               (lambda (_channel) muted))
              ((symbol-function 'disco-state-channel-notification-level)
               (lambda (_channel) level))
              ((symbol-function 'disco-notifications--room-visible-p)
               (lambda (_id) nil)))
      (should (disco-notifications-message-notify-p
               (disco-notifications-test--message)))
      (setq level 1)
      (should-not (disco-notifications-message-notify-p
                   (disco-notifications-test--message)))
      (setq muted t)
      (should (disco-notifications-message-notify-p
               (disco-notifications-test--message t))))))

(ert-deftest disco-notifications-policy-suppresses-self-and-visible-room ()
  (let ((message (disco-notifications-test--message)))
    (cl-letf (((symbol-function 'disco-state-channel)
               (lambda (_id) '((id . "c") (type . 1))))
              ((symbol-function 'disco-state-channel-muted-p) (lambda (_) nil))
              ((symbol-function 'disco-state-channel-notification-level) (lambda (_) 0))
              ((symbol-function 'disco-gateway-current-user-id) (lambda () "other"))
              ((symbol-function 'disco-notifications--room-visible-p) (lambda (_) nil)))
      (should-not (disco-notifications-message-notify-p message)))
    (cl-letf (((symbol-function 'disco-state-channel)
               (lambda (_id) '((id . "c") (type . 1))))
              ((symbol-function 'disco-state-channel-muted-p) (lambda (_) nil))
              ((symbol-function 'disco-state-channel-notification-level) (lambda (_) 0))
              ((symbol-function 'disco-gateway-current-user-id) (lambda () "me"))
              ((symbol-function 'disco-notifications--room-visible-p) (lambda (_) t)))
      (should-not (disco-notifications-message-notify-p message)))))

(ert-deftest disco-notifications-event-hook-dedupes-live-creates ()
  (let ((disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 0)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications--history nil)
        (disco-notifications--history-buffer nil)
        (disco-notifications--last-id nil)
        (disco-notifications--last-display-op nil)
        (disco-notifications-mode t)
        (disco-notifications-delay 0.5)
        cancelled
        scheduled)
    (disco-notifications-test--with-app
      (cl-letf (((symbol-function 'run-with-timer)
                 (lambda (_delay _repeat function &rest arguments)
                   (let ((timer (intern (format "timer-%d"
                                                (1+ (length scheduled))))))
                     (push (list function arguments timer) scheduled)
                     timer)))
                ((symbol-function 'timerp)
                 (lambda (timer) (memq timer '(timer-1 timer-2))))
                ((symbol-function 'cancel-timer)
                 (lambda (timer) (push timer cancelled))))
        (let ((event (list :type 'message-create
                           :message (disco-notifications-test--message t))))
          (disco-notifications--handle-event event)
          (disco-notifications--handle-event event))
        (should (= 1 (length scheduled)))
        (disco-notifications--handle-event '(:type ready))
        (should (= 0 (hash-table-count disco-notifications--seen)))
        (disco-notifications-reset-session-state)
        (should (equal cancelled '(timer-1)))))))

(ert-deftest disco-notifications-reset-invalidates-old-same-id-delivery ()
  (let ((disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 7)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications--history nil)
        (disco-notifications--history-buffer nil)
        (disco-notifications--last-id nil)
        (disco-notifications--last-display-op nil)
        (disco-notifications-mode t)
        (disco-notifications-delay 0.5)
        scheduled
        shown)
    (disco-notifications-test--with-app
      (cl-letf (((symbol-function 'run-with-timer)
                 (lambda (_delay _repeat function &rest arguments)
                   (let ((timer (intern (format "timer-%d"
                                                (1+ (length scheduled))))))
                     (push (list function arguments timer) scheduled)
                     timer)))
                ((symbol-function 'timerp)
                 (lambda (timer) (memq timer '(timer-1 timer-2))))
                ((symbol-function 'cancel-timer) #'ignore)
                ((symbol-function 'disco-notifications--show)
                 (lambda (message &optional _app _generation)
                   (push (alist-get 'content message) shown))))
        (let ((old-message (disco-notifications-test--message t)))
          (setf (alist-get 'content old-message) "OLD_ACCOUNT_SECRET")
          (disco-notifications--handle-event
           (list :type 'message-create :message old-message)))
        (let ((old-callback (car scheduled)))
          (disco-notifications-reset-session-state)
          (let ((new-message (disco-notifications-test--message t)))
            ;; Reusing an opaque id in a new account generation must schedule
            ;; the new message without making the old callback authoritative.
            (setf (alist-get 'content new-message) "NEW_ACCOUNT_MESSAGE")
            (disco-notifications--handle-event
             (list :type 'message-create :message new-message)))
          (let ((new-callback (car scheduled)))
            (apply (car old-callback) (cadr old-callback))
            (apply (car new-callback) (cadr new-callback))))
        (should (equal shown '("NEW_ACCOUNT_MESSAGE")))
        (should-not
         (string-match-p
          "OLD_ACCOUNT_SECRET"
          (prin1-to-string
           (list disco-notifications--history
                 disco-notifications--delay-owners
                 disco-notifications--timeout-owners))))
        (disco-notifications-reset-session-state)))))

(ert-deftest disco-notifications-old-app-timer-is-inert-in-new-app ()
  (let* ((old-app (appkit-start-app 'disco :id (make-symbol "old-account")))
         (new-app nil)
         (disco-runtime--app old-app)
         (disco-notifications--seen (make-hash-table :test #'equal))
         (disco-notifications--seen-order nil)
         (disco-notifications--generation 5)
         (disco-notifications--delay-owners nil)
         (disco-notifications--timeout-owners nil)
         (disco-notifications--history nil)
         (disco-notifications--history-buffer nil)
         (disco-notifications--last-id nil)
         (disco-notifications--last-display-op nil)
         (disco-notifications-mode t)
         (disco-notifications-delay 0.5)
         callback
         owner
         cancelled
         shown)
    (unwind-protect
        (cl-letf (((symbol-function 'run-with-timer)
                   (lambda (_delay _repeat function &rest arguments)
                     (setq callback (cons function arguments))
                     'old-app-timer))
                  ((symbol-function 'timerp)
                   (lambda (timer) (eq timer 'old-app-timer)))
                  ((symbol-function 'cancel-timer)
                   (lambda (timer) (push timer cancelled)))
                  ((symbol-function 'disco-gateway-stop) #'ignore)
                  ((symbol-function 'disco-notifications--show)
                   (lambda (message &optional _app _generation)
                     (push message shown))))
          (let ((message (disco-notifications-test--message t)))
            (setf (alist-get 'content message) "OLD_ACCOUNT_SECRET")
            (setq owner
                  (disco-notifications--schedule-delayed message)))
          (appkit-stop-app old-app)
          (should-not disco-notifications--delay-owners)
          (should-not (plist-get owner :handle))
          (should-not (plist-get owner :timer))
          (should-not
           (string-match-p
            "OLD_ACCOUNT_SECRET"
            (prin1-to-string disco-notifications--delay-owners)))
          (setq new-app
                (appkit-start-app 'disco :id (make-symbol "new-account"))
                disco-runtime--app new-app)
          ;; Generation alone is intentionally unchanged: exact application
          ;; identity and liveness must still reject this queued callback.
          (apply (car callback) (cdr callback))
          (should-not shown)
          (should (equal cancelled '(old-app-timer)))
          (disco-notifications-reset-session-state))
      (when (appkit-app-live-p old-app)
        (appkit-stop-app old-app))
      (when (appkit-app-live-p new-app)
        (appkit-stop-app new-app)))))

(ert-deftest disco-notifications-reset-falls-back-after-handle-cancel-failure ()
  (let* ((app (appkit-start-app 'disco :id (make-symbol "cancel-fallback")))
         (disco-runtime--app app)
         (disco-notifications--seen (make-hash-table :test #'equal))
         (disco-notifications--seen-order nil)
         (disco-notifications--generation 0)
         (disco-notifications--delay-owners nil)
         (disco-notifications--timeout-owners nil)
         (disco-notifications--history nil)
         (disco-notifications--history-buffer nil)
         (disco-notifications--last-id nil)
         (disco-notifications--last-display-op nil)
         (disco-notifications-mode t)
         (disco-notifications-delay 0.5)
         attempts
         cancelled
         owner)
    (unwind-protect
        (cl-letf (((symbol-function 'run-with-timer)
                   (lambda (&rest _) 'fragile-timer))
                  ((symbol-function 'timerp)
                   (lambda (timer) (eq timer 'fragile-timer)))
                  ((symbol-function 'cancel-timer)
                   (lambda (timer)
                     (setq attempts (1+ (or attempts 0)))
                     (if (= attempts 1)
                         (error "first cancellation failed")
                       (push timer cancelled))))
                  ((symbol-function 'disco-gateway-stop) #'ignore))
          (setq owner
                (disco-notifications--schedule-delayed
                 (disco-notifications-test--message t)))
          ;; Appkit's first attempt retires the handle even though the timer
          ;; backend fails.  Reset must use the retained raw timer directly.
          (appkit-stop-app app)
          (should (= attempts 1))
          (should-not (plist-get owner :handle))
          (disco-notifications-reset-session-state)
          (should (= attempts 2))
          (should (equal cancelled '(fragile-timer)))
          (should-not (plist-get owner :handle))
          (should-not (plist-get owner :timer)))
      (when (appkit-app-live-p app)
        (appkit-stop-app app)))))

(ert-deftest disco-notifications-mode-disable-revokes-owned-timers ()
  (let ((original-mode disco-notifications-mode)
        (disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 0)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications--history nil)
        (disco-notifications--history-buffer nil)
        (disco-notifications--last-id nil)
        (disco-notifications--last-display-op nil)
        (disco-notifications-delay 0.5)
        cancelled)
    (disco-notifications-test--with-app
      (unwind-protect
          (cl-letf (((symbol-function 'run-with-timer)
                     (lambda (&rest _) 'mode-delay-timer))
                    ((symbol-function 'timerp)
                     (lambda (timer) (eq timer 'mode-delay-timer)))
                    ((symbol-function 'cancel-timer)
                     (lambda (timer) (push timer cancelled))))
            (disco-notifications-mode 1)
            (disco-notifications--schedule-delayed
             (disco-notifications-test--message t))
            (should disco-notifications--delay-owners)
            (disco-notifications-mode -1)
            (should-not disco-notifications--delay-owners)
            (should (equal cancelled '(mode-delay-timer))))
        (disco-notifications-mode (if original-mode 1 -1))))))

(ert-deftest disco-notifications-reset-clears-history-and-timeout-lifecycle ()
  (let* ((disco-notifications--seen (make-hash-table :test #'equal))
         (disco-notifications--seen-order '("100"))
         (disco-notifications--generation 11)
         (disco-notifications--delay-owners nil)
         (disco-notifications--timeout-owners nil)
         (disco-notifications--history (make-ring 4))
         (history-buffer
          (generate-new-buffer disco-notifications--history-buffer-name))
         (disco-notifications--history-buffer history-buffer)
         (disco-notifications--last-id 'old-notification)
         (disco-notifications--last-display-op 1)
         (disco-notifications--display-sequence 1)
         (disco-notifications--active-display-op 1)
         (disco-notifications-mode t)
         scheduled
         cancelled
         closed
         timeout-owner)
    (disco-notifications-test--with-app
      (unwind-protect
          (progn
            (ring-insert
             disco-notifications--history
             '((id . "100") (content . "OLD_ACCOUNT_SECRET")))
            (with-current-buffer history-buffer
              (special-mode)
              (rename-buffer
               (generate-new-buffer-name " *renamed-disco-history*"))
              (let ((inhibit-read-only t))
                (insert "OLD_ACCOUNT_SECRET")))
            (cl-letf (((symbol-function 'run-with-timer)
                       (lambda (_delay _repeat function &rest arguments)
                         (let ((timer
                                (intern
                                 (format "timer-%d"
                                         (1+ (length scheduled))))))
                           (push (list function arguments timer) scheduled)
                           timer)))
                      ((symbol-function 'timerp)
                       (lambda (timer) (memq timer '(timer-1 timer-2))))
                      ((symbol-function 'cancel-timer)
                       (lambda (timer) (push timer cancelled)))
                      ((symbol-function 'notifications-close-notification)
                       (lambda (id) (push id closed))))
              (disco-notifications--schedule-delayed
               (disco-notifications-test--message t))
              (setq timeout-owner
                    (disco-notifications--schedule-timeout
                     'old-notification
                     disco-runtime--app
                     disco-notifications--generation
                     disco-notifications--active-display-op))
              (disco-notifications-reset-session-state)
              ;; An already-queued old timeout cannot close a new session's
              ;; notification even if the desktop backend reuses identifiers.
              (setq disco-notifications--last-id 'new-notification
                    disco-notifications--last-display-op 'new-display)
              (disco-notifications--timeout-fired timeout-owner))
            (should-not (buffer-live-p history-buffer))
            (should-not disco-notifications--history)
            (should-not disco-notifications--delay-owners)
            (should-not disco-notifications--timeout-owners)
            (should-not disco-notifications--seen-order)
            (should (= 0 (hash-table-count disco-notifications--seen)))
            (should (eq disco-notifications--last-id 'new-notification))
            (should
             (equal (sort (mapcar #'symbol-name cancelled) #'string-lessp)
                    '("timer-1" "timer-2")))
            (should (equal closed '(old-notification))))
        (when (buffer-live-p history-buffer)
          (kill-buffer history-buffer))))))

(ert-deftest disco-notifications-show-closes-id-returned-after-sync-reset ()
  (let ((disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 4)
        (disco-notifications--display-sequence 0)
        (disco-notifications--active-display-op nil)
        (disco-notifications--reset-in-progress nil)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications--history nil)
        (disco-notifications--history-buffer nil)
        (disco-notifications--last-id nil)
        (disco-notifications--last-display-op nil)
        (disco-notifications-mode t)
        (disco-notifications-timeout nil)
        closed)
    (disco-notifications-test--with-app
      (cl-letf (((symbol-function 'disco-notifications-message-notify-p)
                 (lambda (_) t))
                ((symbol-function 'disco-notifications--title)
                 (lambda (&rest _) "title"))
                ((symbol-function 'disco-notifications--body)
                 (lambda (_) "body"))
                ((symbol-function 'disco-notifications--message-ping-p)
                 (lambda (_) nil))
                ((symbol-function 'notifications-notify)
                 (lambda (&rest _)
                   (disco-notifications-reset-session-state)
                   'late-id))
                ((symbol-function 'notifications-close-notification)
                 (lambda (id) (push id closed))))
        (disco-notifications--show
         (disco-notifications-test--message) app
         disco-notifications--generation)
        (should-not disco-notifications--last-id)
        (should-not disco-notifications--history)
        (should-not disco-notifications--timeout-owners)
        (should (equal closed '(late-id)))))))

(ert-deftest disco-notifications-nested-show-keeps-newer-display-authoritative ()
  (let ((disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 3)
        (disco-notifications--display-sequence 0)
        (disco-notifications--active-display-op nil)
        (disco-notifications--reset-in-progress nil)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications--history nil)
        (disco-notifications--history-buffer nil)
        (disco-notifications--last-id nil)
        (disco-notifications--last-display-op nil)
        (disco-notifications-mode t)
        (disco-notifications-timeout nil)
        (outer (disco-notifications-test--message))
        (inner (disco-notifications-test--message))
        (notify-count 0)
        closed)
    (setf (alist-get 'id outer) "outer"
          (alist-get 'content outer) "outer message"
          (alist-get 'id inner) "inner"
          (alist-get 'content inner) "inner message")
    (disco-notifications-test--with-app
      (let ((generation disco-notifications--generation))
        (cl-letf (((symbol-function 'disco-notifications-message-notify-p)
                   (lambda (_) t))
                  ((symbol-function 'disco-notifications--title)
                   (lambda (&rest _) "title"))
                  ((symbol-function 'disco-notifications--body)
                   (lambda (_) "body"))
                  ((symbol-function 'disco-notifications--message-ping-p)
                   (lambda (_) nil))
                  ((symbol-function 'notifications-notify)
                   (lambda (&rest _)
                     (cl-incf notify-count)
                     (if (= notify-count 1)
                         (progn
                           (disco-notifications--show inner app generation)
                           'outer-id)
                       'inner-id)))
                  ((symbol-function 'notifications-close-notification)
                   (lambda (id) (push id closed))))
          (disco-notifications--show outer app generation)
          (should (eq disco-notifications--last-id 'inner-id))
          (should (= 2 notify-count))
          (should (equal closed '(outer-id)))
          (should
           (equal (mapcar (lambda (message) (alist-get 'content message))
                          (ring-elements disco-notifications--history))
                  '("inner message"))))))))

(ert-deftest disco-notifications-nested-policy-or-preparation-stales-outer ()
  (dolist (boundary '(policy preparation))
    (let ((disco-notifications--seen (make-hash-table :test #'equal))
          (disco-notifications--seen-order nil)
          (disco-notifications--generation 3)
          (disco-notifications--display-sequence 0)
          (disco-notifications--active-display-op nil)
          (disco-notifications--reset-in-progress nil)
          (disco-notifications--delay-owners nil)
          (disco-notifications--timeout-owners nil)
          (disco-notifications--history nil)
          (disco-notifications--history-buffer nil)
          (disco-notifications--last-id nil)
          (disco-notifications--last-display-op nil)
          (disco-notifications-mode t)
          (disco-notifications-timeout nil)
          (outer (disco-notifications-test--message))
          (inner (disco-notifications-test--message))
          nested-p
          (notify-count 0)
          closed)
      (setf (alist-get 'id outer) "outer-reservation"
            (alist-get 'content outer) "outer reservation"
            (alist-get 'id inner) "inner-reservation"
            (alist-get 'content inner) "inner reservation")
      (disco-notifications-test--with-app
        (let ((generation disco-notifications--generation))
          (cl-labels
              ((maybe-nest (message at-boundary)
                 (when (and (eq boundary at-boundary)
                            (equal (alist-get 'id message)
                                   "outer-reservation")
                            (not nested-p))
                   (setq nested-p t)
                   (disco-notifications--show inner app generation))))
            (cl-letf (((symbol-function 'disco-notifications-message-notify-p)
                       (lambda (message)
                         (maybe-nest message 'policy)
                         t))
                      ((symbol-function 'disco-notifications--title)
                       (lambda (message &rest _)
                         (maybe-nest message 'preparation)
                         (alist-get 'id message)))
                      ((symbol-function 'disco-notifications--body)
                       (lambda (_) "body"))
                      ((symbol-function 'disco-notifications--message-ping-p)
                       (lambda (_) nil))
                      ((symbol-function 'notifications-notify)
                       (lambda (&rest args)
                         (cl-incf notify-count)
                         (intern (concat (plist-get args :title) "-backend"))))
                      ((symbol-function 'notifications-close-notification)
                       (lambda (id) (push id closed))))
              (disco-notifications--show outer app generation)
              (ert-info ((format "synchronous boundary: %S" boundary))
                (should (eq disco-notifications--last-id
                            'inner-reservation-backend))
                (should (= notify-count 1))
                (should-not closed)
                (should
                 (equal
                  (mapcar (lambda (message) (alist-get 'content message))
                          (ring-elements disco-notifications--history))
                  '("inner reservation")))))))))))

(ert-deftest disco-notifications-nested-show-preserves-reused-current-id ()
  (let ((disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 3)
        (disco-notifications--display-sequence 0)
        (disco-notifications--active-display-op nil)
        (disco-notifications--reset-in-progress nil)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications--history nil)
        (disco-notifications--history-buffer nil)
        (disco-notifications--last-id nil)
        (disco-notifications--last-display-op nil)
        (disco-notifications-mode t)
        (disco-notifications-timeout nil)
        (outer (disco-notifications-test--message))
        (inner (disco-notifications-test--message))
        (notify-count 0)
        closed)
    (setf (alist-get 'id outer) "outer-reused"
          (alist-get 'content outer) "outer reused id"
          (alist-get 'id inner) "inner-reused"
          (alist-get 'content inner) "inner reused id")
    (disco-notifications-test--with-app
      (let ((generation disco-notifications--generation))
        (cl-letf (((symbol-function 'disco-notifications-message-notify-p)
                   (lambda (_) t))
                  ((symbol-function 'disco-notifications--title)
                   (lambda (&rest _) "title"))
                  ((symbol-function 'disco-notifications--body)
                   (lambda (_) "body"))
                  ((symbol-function 'disco-notifications--message-ping-p)
                   (lambda (_) nil))
                  ((symbol-function 'notifications-notify)
                   (lambda (&rest _)
                     (cl-incf notify-count)
                     (when (= notify-count 1)
                       (disco-notifications--show inner app generation))
                     'same-id))
                  ((symbol-function 'notifications-close-notification)
                   (lambda (id) (push id closed))))
          (disco-notifications--show outer app generation)
          (should (eq disco-notifications--last-id 'same-id))
          (should
           (equal disco-notifications--last-display-op
                  disco-notifications--active-display-op))
          (should (= 2 notify-count))
          (should-not closed)
          (should
           (equal (mapcar (lambda (message) (alist-get 'content message))
                          (ring-elements disco-notifications--history))
                  '("inner reused id"))))))))

(ert-deftest disco-notifications-account-switch-preserves-reused-current-id ()
  (let* ((old-app (appkit-start-app 'disco :id (make-symbol "old-display")))
         new-app
         (disco-runtime--app old-app)
         (disco-notifications--seen (make-hash-table :test #'equal))
         (disco-notifications--seen-order nil)
         (disco-notifications--generation 6)
         (disco-notifications--display-sequence 0)
         (disco-notifications--active-display-op nil)
         (disco-notifications--reset-in-progress nil)
         (disco-notifications--delay-owners nil)
         (disco-notifications--timeout-owners nil)
         (disco-notifications--history nil)
         (disco-notifications--history-buffer nil)
         (disco-notifications--last-id nil)
         (disco-notifications--last-display-op nil)
         (disco-notifications-mode t)
         (disco-notifications-timeout nil)
         (outer (disco-notifications-test--message))
         (inner (disco-notifications-test--message))
         (old-generation disco-notifications--generation)
         (notify-count 0)
         closed)
    (setf (alist-get 'content outer) "old account outer"
          (alist-get 'content inner) "new account inner")
    (unwind-protect
        (cl-letf (((symbol-function 'disco-notifications-message-notify-p)
                   (lambda (_) t))
                  ((symbol-function 'disco-notifications--title)
                   (lambda (&rest _) "title"))
                  ((symbol-function 'disco-notifications--body)
                   (lambda (_) "body"))
                  ((symbol-function 'disco-notifications--message-ping-p)
                   (lambda (_) nil))
                  ((symbol-function 'disco-gateway-stop) #'ignore)
                  ((symbol-function 'notifications-notify)
                   (lambda (&rest _)
                     (cl-incf notify-count)
                     (when (= notify-count 1)
                       (disco-notifications-reset-session-state)
                       (appkit-stop-app old-app)
                       (setq new-app
                             (appkit-start-app
                              'disco :id (make-symbol "new-display"))
                             disco-runtime--app new-app)
                       (disco-notifications--show
                        inner new-app disco-notifications--generation))
                     'same-account-switched-id))
                  ((symbol-function 'notifications-close-notification)
                   (lambda (id) (push id closed))))
          (disco-notifications--show outer old-app old-generation)
          (should (eq disco-runtime--app new-app))
          (should (eq disco-notifications--last-id
                      'same-account-switched-id))
          (should
           (equal disco-notifications--last-display-op
                  disco-notifications--active-display-op))
          (should (= 2 notify-count))
          (should-not closed)
          (should
           (equal (mapcar (lambda (message) (alist-get 'content message))
                          (ring-elements disco-notifications--history))
                  '("new account inner"))))
      (when (appkit-app-live-p old-app)
        (appkit-stop-app old-app))
      (when (appkit-app-live-p new-app)
        (appkit-stop-app new-app)))))

(ert-deftest disco-notifications-timeout-revalidates-after-sync-cancel ()
  (let ((disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 4)
        (disco-notifications--display-sequence 1)
        (disco-notifications--active-display-op 1)
        (disco-notifications--reset-in-progress nil)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications--history nil)
        (disco-notifications--history-buffer nil)
        (disco-notifications--last-id 'shared-id)
        (disco-notifications--last-display-op 1)
        (disco-notifications-mode t)
        (disco-notifications-timeout nil)
        reentered
        closed)
    (disco-notifications-test--with-app
      (let ((owner (list :app app :generation 4 :display-op 1
                         :id 'shared-id :timer nil :handle nil))
            (new-message (disco-notifications-test--message)))
        (setf (alist-get 'content new-message) "new notification")
        (setq disco-notifications--timeout-owners (list owner))
        (cl-letf (((symbol-function 'disco-notifications-message-notify-p)
                   (lambda (_) t))
                  ((symbol-function 'disco-notifications--title)
                   (lambda (&rest _) "title"))
                  ((symbol-function 'disco-notifications--body)
                   (lambda (_) "body"))
                  ((symbol-function 'disco-notifications--message-ping-p)
                   (lambda (_) nil))
                  ((symbol-function 'notifications-notify)
                   (lambda (&rest _) 'shared-id))
                  ((symbol-function 'notifications-close-notification)
                   (lambda (id) (push id closed)))
                  ((symbol-function 'disco-notifications--cancel-owner-timer)
                   (lambda (_owner)
                     (unless reentered
                       (setq reentered t)
                       (disco-notifications-reset-session-state)
                       (disco-notifications--show
                        new-message app disco-notifications--generation)))))
          (disco-notifications--timeout-fired owner)
          (should (eq disco-notifications--last-id 'shared-id))
          (should (equal closed '(shared-id)))
          (should
           (equal (mapcar (lambda (message) (alist-get 'content message))
                          (ring-elements disco-notifications--history))
                  '("new notification"))))))))

(ert-deftest disco-notifications-closes-returned-id-on-history-failure ()
  (let ((disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 2)
        (disco-notifications--display-sequence 0)
        (disco-notifications--active-display-op nil)
        (disco-notifications--reset-in-progress nil)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications--history nil)
        (disco-notifications--history-buffer nil)
        (disco-notifications--last-id nil)
        (disco-notifications--last-display-op nil)
        (disco-notifications-mode t)
        (disco-notifications-timeout nil)
        closed)
    (disco-notifications-test--with-app
      (cl-letf (((symbol-function 'disco-notifications-message-notify-p)
                 (lambda (_) t))
                ((symbol-function 'disco-notifications--title)
                 (lambda (&rest _) "title"))
                ((symbol-function 'disco-notifications--body)
                 (lambda (_) "body"))
                ((symbol-function 'disco-notifications--message-ping-p)
                 (lambda (_) nil))
                ((symbol-function 'notifications-notify)
                 (lambda (&rest _) 'unpublished-id))
                ((symbol-function 'ring-insert)
                 (lambda (&rest _) (error "history write failed")))
                ((symbol-function 'notifications-close-notification)
                 (lambda (id) (push id closed))))
        (should-error
         (disco-notifications--show
          (disco-notifications-test--message) app
          disco-notifications--generation))
        (should-not disco-notifications--last-id)
        (should-not disco-notifications--last-display-op)
        (should (equal closed '(unpublished-id)))))))

(ert-deftest disco-notifications-preparation-error-keeps-old-timeout-current ()
  (let ((disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 9)
        (disco-notifications--display-sequence 1)
        (disco-notifications--active-display-op 1)
        (disco-notifications--reset-in-progress nil)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications--history nil)
        (disco-notifications--history-buffer nil)
        (disco-notifications--last-id 'old-id)
        (disco-notifications--last-display-op 1)
        (disco-notifications-mode t)
        closed)
    (disco-notifications-test--with-app
      (let ((owner (list :app app :generation 9 :display-op 1
                         :id 'old-id :timer nil :handle nil)))
        (setq disco-notifications--timeout-owners (list owner))
        (cl-letf (((symbol-function 'disco-notifications-message-notify-p)
                   (lambda (_) t))
                  ((symbol-function 'disco-notifications--title)
                   (lambda (&rest _) (error "title failed")))
                  ((symbol-function 'notifications-close-notification)
                   (lambda (id) (push id closed))))
          (should-error
           (disco-notifications--show
            (disco-notifications-test--message) app
            disco-notifications--generation))
          (should (= disco-notifications--active-display-op 1))
          (should (memq owner disco-notifications--timeout-owners))
          (disco-notifications--timeout-fired owner)
          (should-not disco-notifications--last-id)
          (should (equal closed '(old-id))))))))

(ert-deftest disco-notifications-reset-drains-history-kill-successors ()
  (let* ((disco-notifications--seen (make-hash-table :test #'equal))
         (disco-notifications--seen-order nil)
         (disco-notifications--generation 1)
         (disco-notifications--display-sequence 0)
         (disco-notifications--active-display-op nil)
         (disco-notifications--reset-in-progress nil)
         (disco-notifications--delay-owners nil)
         (disco-notifications--timeout-owners nil)
         (disco-notifications--history nil)
         (history-buffer (generate-new-buffer " *history-drain-old*"))
         (disco-notifications--history-buffer history-buffer)
         (disco-notifications--last-id nil)
         (disco-notifications--last-display-op nil)
         successor)
    (unwind-protect
        (progn
          (with-current-buffer history-buffer
            (special-mode)
            (setq-local disco-notifications--history-owner-p t)
            (let ((inhibit-read-only t))
              (insert "OLD_ACCOUNT_SECRET old history"))
            (add-hook
             'kill-buffer-hook
             (lambda ()
               (unless successor
                 (setq successor
                       (generate-new-buffer " *history-drain-successor*")
                       disco-notifications--history-buffer successor)
                 (with-current-buffer successor
                   (special-mode)
                   (setq-local disco-notifications--history-owner-p t)
                   (let ((inhibit-read-only t))
                     (insert "OLD_ACCOUNT_SECRET copied successor")))))
             nil t))
          (disco-notifications-reset-session-state)
          (should-not (buffer-live-p history-buffer))
          (should-not (buffer-live-p successor))
          (should-not disco-notifications--history-buffer)
          (should-not
           (string-match-p
            "OLD_ACCOUNT_SECRET"
            (prin1-to-string
             (list disco-notifications--history
                   disco-notifications--history-buffer)))))
      (dolist (buffer (list history-buffer successor))
        (when (buffer-live-p buffer)
          (with-current-buffer buffer
            (let ((kill-buffer-hook nil))
              (kill-buffer buffer))))))))

(ert-deftest disco-notifications-reset-forces-history-past-change-hooks ()
  (let* ((disco-notifications--seen (make-hash-table :test #'equal))
         (disco-notifications--seen-order nil)
         (disco-notifications--generation 1)
         (disco-notifications--display-sequence 0)
         (disco-notifications--active-display-op nil)
         (disco-notifications--reset-in-progress nil)
         (disco-notifications--delay-owners nil)
         (disco-notifications--timeout-owners nil)
         (disco-notifications--history nil)
         (history-buffer (generate-new-buffer " *history-hostile-hooks*"))
         (disco-notifications--history-buffer history-buffer)
         (disco-notifications--last-id nil)
         (disco-notifications--last-display-op nil))
    (unwind-protect
        (progn
          (with-current-buffer history-buffer
            (special-mode)
            (setq-local disco-notifications--history-owner-p t)
            (let ((inhibit-read-only t))
              (insert "OLD_ACCOUNT_SECRET hostile history"))
            (add-hook 'before-change-functions
                      (lambda (&rest _)
                        (error "refuse privacy erase"))
                      nil t)
            (add-hook 'kill-buffer-hook
                      (lambda () (error "refuse normal kill"))
                      nil t))
          (disco-notifications-reset-session-state)
          (should-not (buffer-live-p history-buffer)))
      (when (buffer-live-p history-buffer)
        (with-current-buffer history-buffer
          (let ((before-change-functions nil)
                (kill-buffer-hook nil))
            (kill-buffer history-buffer)))))))

(ert-deftest disco-notifications-reset-barrier-rejects-reentrant-work ()
  (let* ((disco-notifications--seen (make-hash-table :test #'equal))
         (disco-notifications--seen-order nil)
         (disco-notifications--generation 8)
         (disco-notifications--display-sequence 0)
         (disco-notifications--active-display-op nil)
         (disco-notifications--reset-in-progress nil)
         (disco-notifications--delay-owners nil)
         (disco-notifications--timeout-owners nil)
         (disco-notifications--history nil)
         (history-buffer (generate-new-buffer " *notification-reset-reentry*"))
         (disco-notifications--history-buffer history-buffer)
         (disco-notifications--last-id nil)
         (disco-notifications--last-display-op nil)
         (disco-notifications-mode t)
         (disco-notifications-delay 0.5)
         (scheduled 0)
         cancelled)
    (disco-notifications-test--with-app
      (unwind-protect
          (progn
            (with-current-buffer history-buffer
              (setq-local disco-notifications--history-owner-p t)
              (add-hook
               'kill-buffer-hook
               (lambda ()
                 (disco-notifications--schedule-delayed
                  (disco-notifications-test--message t)))
               nil t))
            (cl-letf (((symbol-function 'run-with-timer)
                       (lambda (&rest _)
                         (cl-incf scheduled)
                         'reset-reentry-timer))
                      ((symbol-function 'timerp)
                       (lambda (timer) (eq timer 'reset-reentry-timer)))
                      ((symbol-function 'cancel-timer)
                       (lambda (timer)
                         (push timer cancelled)
                         (disco-notifications--handle-event
                          (list :type 'message-create
                                :message
                                (disco-notifications-test--message t))))))
              (disco-notifications--schedule-delayed
               (disco-notifications-test--message t))
              (disco-notifications-reset-session-state))
            (should (= scheduled 1))
            (should (equal cancelled '(reset-reentry-timer)))
            (should-not disco-notifications--delay-owners)
            (should-not disco-notifications--timeout-owners)
            (should-not disco-notifications--seen-order)
            (should (= 0 (hash-table-count disco-notifications--seen))))
        (when (buffer-live-p history-buffer)
          (kill-buffer history-buffer))))))

(ert-deftest disco-notifications-sync-timer-does-not-retain-retired-owner ()
  (let ((disco-notifications--seen (make-hash-table :test #'equal))
        (disco-notifications--seen-order nil)
        (disco-notifications--generation 2)
        (disco-notifications--reset-in-progress nil)
        (disco-notifications--delay-owners nil)
        (disco-notifications--timeout-owners nil)
        (disco-notifications-mode t)
        cancelled
        shown)
    (disco-notifications-test--with-app
      (cl-letf (((symbol-function 'run-with-timer)
                 (lambda (_delay _repeat function &rest arguments)
                   (apply function arguments)
                   'synchronous-timer))
                ((symbol-function 'timerp)
                 (lambda (timer) (eq timer 'synchronous-timer)))
                ((symbol-function 'cancel-timer)
                 (lambda (timer) (push timer cancelled)))
                ((symbol-function 'disco-notifications--show)
                 (lambda (message &rest _)
                   (push message shown))))
        (disco-notifications--schedule-delayed
         (disco-notifications-test--message t))
        (should (= 1 (length shown)))
        (should-not disco-notifications--delay-owners)
        (should-not disco-notifications--timeout-owners)
        (should (equal cancelled '(synchronous-timer)))))))

(provide 'disco-notifications-test)

;;; disco-notifications-test.el ends here
