;;; disco-directory-test.el --- Tests for lazy Discord directory -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'disco-directory)

(ert-deftest disco-directory-index-refresh-does-not-hydrate-guilds ()
  (disco-state-reset)
  (disco-directory-reset)
  (let (guild-channel-requested completed-errors)
    (cl-letf (((symbol-function 'disco-api-user-guilds-async)
               (lambda (&rest args)
                 (funcall (plist-get args :on-success)
                          '(((id . "g1") (name . "Guild"))))))
              ((symbol-function 'disco-api-user-private-channels-async)
               (lambda (&rest args)
                 (funcall (plist-get args :on-success) '())))
              ((symbol-function 'disco-api-guild-channels-async)
               (lambda (&rest _args)
                 (setq guild-channel-requested t))))
      (disco-directory-refresh-index-async
       :on-complete (lambda (errors) (setq completed-errors errors)))
      (should (equal '("g1")
                     (mapcar (lambda (guild) (alist-get 'id guild))
                             (disco-state-guilds))))
      (should-not guild-channel-requested)
      (should-not completed-errors)
      (should-not (disco-state-guild-channels-loaded-p "g1")))))

(ert-deftest disco-directory-guild-load-is-coalesced-and-marks-snapshot-complete ()
  (disco-state-reset)
  (disco-directory-reset)
  (disco-state-set-guilds '(((id . "g1") (name . "Guild"))))
  (let ((calls 0)
        success)
    (cl-letf (((symbol-function 'disco-api-guild-channels-async)
               (lambda (_guild-id &rest args)
                 (cl-incf calls)
                 (setq success (plist-get args :on-success)))))
      (should (eq 'loading (disco-directory-load-guild-async "g1")))
      (should (eq 'loading (disco-directory-load-guild-async "g1")))
      (should (= calls 1))
      (funcall success '(((id . "c1") (guild_id . "g1") (type . 0))))
      (should (eq 'loaded (disco-directory-guild-status "g1")))
      (should (disco-state-guild-channels-loaded-p "g1"))
      (should (equal "c1"
                     (alist-get 'id (car (disco-state-guild-channels "g1"))))))))

(ert-deftest disco-directory-guild-load-error-is-explicit-and-retryable ()
  (disco-state-reset)
  (disco-directory-reset)
  (disco-state-set-guilds '(((id . "g1") (name . "Guild"))))
  (let ((calls 0)
        failure)
    (cl-letf (((symbol-function 'disco-api-guild-channels-async)
               (lambda (_guild-id &rest args)
                 (cl-incf calls)
                 (setq failure (plist-get args :on-error)))))
      (disco-directory-load-guild-async "g1")
      (funcall failure '(:status 500))
      (should (eq 'error (disco-directory-guild-status "g1")))
      (disco-directory-load-guild-async "g1")
      (should (= calls 2)))))

(provide 'disco-directory-test)

;;; disco-directory-test.el ends here
