;;; disco-room-selection-test.el --- Message selection contracts -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'disco-room-test-support)
(require 'disco-transient)

(defun disco-room-selection-test-seed ()
  "Seed three canonical messages and a draft in the current fixture room."
  (disco-state-upsert-channel
   `((id . ,disco-room--channel-id) (type . 0) (permissions . "8")))
  (dolist (id '("100" "200" "300"))
    (disco-state-upsert-message
     disco-room--channel-id
     `((id . ,id) (channel_id . ,disco-room--channel-id)
       (content . ,(concat "body " id)))))
  (disco-room-test-establish-latest-window)
  (disco-room-render)
  (disco-room--set-draft "unsent draft"))

(ert-deftest disco-room-selection-outlives-projection-but-not-owner-or-deletion ()
  (disco-room-test-with-surface "selection"
    (disco-room-selection-test-seed)
    (goto-char (appkit-chat-timeline-key-position "100"))
    (disco-msg-mark-toggle)
    (goto-char (appkit-chat-timeline-key-position "300"))
    (disco-msg-mark-toggle)
    (let ((captured (disco-msg-capture-selection)))
      ;; Empty projection is not deletion; rebuild must retain noncontiguous marks.
      (appkit-chat-timeline-sync nil)
      (should (equal '("100" "300") (disco-room--marked-ids)))
      (disco-room-render)
      (disco-state-upsert-message "selection" '((id . "100") (channel_id . "selection")
						(content . "replacement")))
      (should (equal "replacement" (alist-get 'content
                                              (car (disco-msg-selection-messages captured)))))
      (disco-msg-toggle-marks)
      (should-not (disco-room--marked-ids))
      (disco-state-delete-message "selection" "300")
      (appkit-surface-send surface '(gateway-event (:type message-delete :message-id "300"
                                                          :channel-id "selection")))
      (disco-msg-toggle-marks)
      (should (equal '("100") (disco-room--marked-ids)))
      (should (equal "unsent draft" (disco-room--current-draft)))
      (appkit-surface-stop surface)
      (should-error (disco-msg-selection-messages captured) :type 'user-error)
      (disco-room--ensure-surface)
      (should-not (disco-room--marked-ids))
      (should-error (disco-msg-selection-messages captured) :type 'user-error))))

(ert-deftest disco-room-selection-menu-snapshot-wins-over-changing-point-and-marks ()
  (disco-room-test-with-surface "selection"
    (disco-room-selection-test-seed)
    (disco-room--mark-message 'toggle "300")
    (let* ((transient-mark-mode t)
           (begin (appkit-chat-timeline-key-position "100"))
           (end (appkit-chat-timeline-key-position "200")))
      (goto-char begin)
      (set-mark end)
      (setq mark-active t)
      (let* ((selection (disco-msg-capture-selection))
             (transient-current-prefix
              (clone (get 'disco-transient-msg-operate 'transient--prefix) :scope selection))
             (transient--prefix nil))
        (deactivate-mark)
        (goto-char (appkit-chat-timeline-key-position "300"))
        (disco-state-upsert-message "selection" '((id . "100") (channel_id . "selection")
                                                  (content . "new body")))
        (call-interactively #'disco-msg-copy-text)
        (should (equal "new body" (current-kill 0 t)))
        (call-interactively #'disco-msg-copy-link)
        (should (equal "https://discord.com/channels/@me/selection/100" (current-kill 0 t)))
        (disco-state-delete-message "selection" "100")
        (should-error (call-interactively #'disco-msg-copy-text) :type 'user-error)))
    (disco-room--mark-message 'toggle "200")
    (should-error (call-interactively #'disco-msg-reply) :type 'user-error)
    (should-error (call-interactively #'disco-room-edit-message) :type 'user-error)
    (should-error (call-interactively #'disco-msg-open-thread) :type 'user-error)
    (should (equal "unsent draft" (disco-room--current-draft)))))

(ert-deftest disco-room-selection-forward-serializes-failures-and-revokes-late-results ()
  (disco-room-test-with-surface "selection"
    (disco-room-selection-test-seed)
    (let (requests)
      (cl-letf (((symbol-function 'disco-api-forward-message-async)
                 (lambda (_channel id _source &rest args)
                   (setq requests (append requests (list (cons id args))))
                   (appkit-register-handle (plist-get args :owner) 'test-request nil #'ignore)))
                ((symbol-function 'read-string) (lambda (&rest _) "")))
        (dolist (id '("100" "200" "300")) (disco-room--mark-message 'toggle id))
        (call-interactively #'disco-msg-forward)
        (should (equal '("100") (mapcar #'car requests)))
        (should (disco-room--forward-unavailable-reason))
        (let ((success (plist-get (cdar requests) :on-success)))
          (funcall success '((id . "400") (channel_id . "selection") (content . "forwarded")))
          (funcall success '((id . "999") (channel_id . "selection") (content . "duplicate"))))
        (disco-room-test-drain surface)
        (should (equal '("100" "200") (mapcar #'car requests)))
        (should-not (disco-room--resolve-message "999"))
        (funcall (plist-get (cdr (nth 1 requests)) :on-error) '(:message "denied"))
        (disco-room-test-drain surface)
        (should (equal '("100" "200" "300") (mapcar #'car requests)))
        (funcall (plist-get (cdr (nth 2 requests)) :on-success)
                 '((id . "500") (channel_id . "selection") (content . "forwarded")))
        (disco-room-test-drain surface)
        (should-not (disco-room-operation-current))
        (should (equal '("200") (disco-room--marked-ids)))
        (should (equal "unsent draft" (disco-room--current-draft)))
        (should (string-match-p "2 succeeded, 1 failed"
                                (disco-room-operation-status (appkit-surface-model surface))))
        ;; A second batch must not continue or merge a reply after owner closure.
        (disco-room-operation-begin 'forward
                                    '((:id "100" :source-channel "selection")
                                      (:id "300" :source-channel "selection")))
        (appkit-surface-stop surface)
        (funcall (plist-get (cdr (nth 3 requests)) :on-success)
                 '((id . "600") (channel_id . "selection") (content . "late")))
        (should (= 4 (length requests)))
        (should-not (disco-room--channel-message-by-id "selection" "600"))))))

(ert-deftest disco-room-selection-delete-preflights-all-and-retains-failures ()
  (disco-room-test-with-surface "selection"
    (disco-room-selection-test-seed)
    (let ((confirmations 0) requests)
      (cl-letf (((symbol-function 'y-or-n-p)
                 (lambda (&rest _) (cl-incf confirmations) t))
                ((symbol-function 'disco-api-delete-message-async)
                 (lambda (_channel id &rest args)
                   (setq requests (append requests (list (cons id args))))
                   (appkit-register-handle (plist-get args :owner) 'test-request nil #'ignore))))
        (disco-room--mark-message 'toggle "100")
        (disco-room--mark-message 'toggle "300")
        (cl-letf (((symbol-function 'disco-room--delete-message-unavailable-reason)
                   (lambda (msg) (when (equal (disco-msg-id msg) "300") "not permitted"))))
          (should-error (call-interactively #'disco-msg-delete) :type 'user-error))
        (should-not requests)
        (should (zerop confirmations))
        (call-interactively #'disco-msg-delete)
        (should (= confirmations 1))
        (funcall (plist-get (cdar requests) :on-success) nil)
        (disco-room-test-drain surface)
        (funcall (plist-get (cdr (nth 1 requests)) :on-error) '(:message "denied"))
        (disco-room-test-drain surface)
        (should-not (disco-room--resolve-message "100"))
        (should (equal '("300") (disco-room--marked-ids)))
        (should (disco-room--resolve-message "200"))
        (should (equal "unsent draft" (disco-room--current-draft)))))))

(provide 'disco-room-selection-test)
;;; disco-room-selection-test.el ends here
