;;; disco-directory-test.el --- Tests for lazy Discord directory -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'disco-directory)

(defun disco-directory-test--seed-visible-forum ()
  "Reset directory state and install one accessible forum parent."
  (disco-state-reset)
  (disco-directory-reset)
  (disco-state-set-guilds '(((id . "guild") (name . "Guild"))))
  (disco-state-put-channels
   "guild" '(((id . "forum") (guild_id . "guild") (type . 15)
               (permissions . "1024")))))

(ert-deftest disco-directory-index-refresh-does-not-hydrate-guilds ()
  (disco-state-reset)
  (disco-directory-reset)
  (let (guild-channel-requested completion)
    (cl-letf (((symbol-function 'disco-api-user-guilds-async)
               (lambda (&rest args)
                 (funcall (plist-get args :on-success)
                          '(((id . "g1") (name . "Guild"))))))
              ((symbol-function 'disco-api-user-private-channels-async)
               (lambda (&rest args)
                 (funcall (plist-get args :on-success) '())))
              ((symbol-function 'disco-api-guild-channels-async)
               (lambda (&rest _args)
                 (setq guild-channel-requested t))))
      (disco-directory-refresh-index-async
       :on-complete (lambda (result) (setq completion result)))
      (should (equal '("g1")
                     (mapcar (lambda (guild) (alist-get 'id guild))
                             (disco-state-guilds))))
      (should-not guild-channel-requested)
      (should (eq 'completed (plist-get completion :status)))
      (should-not (plist-get completion :errors))
      (should-not (disco-state-guild-channels-loaded-p "g1")))))

(ert-deftest disco-directory-index-refresh-supersedes-with-exactly-one-completion ()
  (disco-state-reset)
  (disco-directory-reset)
  (let (guild-successes private-successes first-results second-results events)
    (let ((disco-directory-event-hook
           (list (lambda (event) (push (plist-get event :type) events)))))
      (cl-letf (((symbol-function 'disco-api-user-guilds-async)
                 (lambda (&rest args)
                   (push (plist-get args :on-success) guild-successes)))
                ((symbol-function 'disco-api-user-private-channels-async)
                 (lambda (&rest args)
                   (push (plist-get args :on-success) private-successes))))
        (disco-directory-refresh-index-async
         :on-complete (lambda (result) (push result first-results)))
        (disco-directory-refresh-index-async
         :on-complete (lambda (result) (push result second-results)))
        (should (= 1 (length first-results)))
        (should (eq 'superseded
                    (plist-get (car first-results) :status)))
        ;; Returning both stale endpoints cannot settle or mutate twice.
        (funcall (cadr guild-successes)
                 '(((id . "stale") (name . "Stale"))))
        (funcall (cadr private-successes)
                 '(((id . "stale-dm") (type . 1))))
        (should (= 1 (length first-results)))
        (should-not (disco-state-guilds))
        (should-not (disco-state-private-channels))
        ;; The replacing request completes normally.
        (funcall (car guild-successes)
                 '(((id . "fresh") (name . "Fresh"))))
        (funcall (car guild-successes)
                 '(((id . "duplicate") (name . "Duplicate"))))
        (should-not second-results)
        (funcall (car private-successes)
                 '(((id . "fresh-dm") (type . 1))))
        (should (= 1 (length second-results)))
        (should (eq 'completed
                    (plist-get (car second-results) :status)))
        (should (equal '("fresh")
                       (mapcar (lambda (guild) (alist-get 'id guild))
                               (disco-state-guilds))))
        (should (= 1 (seq-count (lambda (type) (eq type 'index-superseded))
                                events)))
        (should (= 1 (seq-count (lambda (type) (eq type 'index-loaded))
                                events)))))))

(ert-deftest disco-directory-index-loaded-event-exposes-endpoint-errors ()
  (disco-state-reset)
  (disco-directory-reset)
  (let (completion loaded-event)
    (let ((disco-directory-event-hook
           (list (lambda (event)
                   (when (eq (plist-get event :type) 'index-loaded)
                     (setq loaded-event event))))))
      (cl-letf (((symbol-function 'disco-api-user-guilds-async)
                 (lambda (&rest args)
                   (funcall (plist-get args :on-error) '(:status 503))))
                ((symbol-function 'disco-api-user-private-channels-async)
                 (lambda (&rest args)
                   (funcall (plist-get args :on-success) '()))))
        (disco-directory-refresh-index-async
         :on-complete (lambda (result) (setq completion result)))
        (should (eq 'completed (plist-get completion :status)))
        (should (equal '((guilds :status 503))
                       (plist-get completion :errors)))
        (should (equal (plist-get completion :errors)
                       (plist-get loaded-event :errors)))
        (should (eq 'completed (plist-get loaded-event :status)))))))

(ert-deftest disco-directory-index-refresh-cancels-on-new-gateway-session ()
  (unwind-protect
      (let ((disco-gateway--session-generation 20))
        (disco-state-reset)
        (disco-directory-reset)
        (let (guild-success private-success results)
          (cl-letf (((symbol-function 'disco-api-user-guilds-async)
                     (lambda (&rest args)
                       (setq guild-success (plist-get args :on-success))))
                    ((symbol-function 'disco-api-user-private-channels-async)
                     (lambda (&rest args)
                       (setq private-success (plist-get args :on-success)))))
            (disco-directory-refresh-index-async
             :on-complete (lambda (result) (push result results)))
            (cl-incf disco-gateway--session-generation)
            ;; Any directory entry point observes READY and cancels the old
            ;; request without waiting for either HTTP endpoint.
            (disco-directory-guild-status "absent")
            (should (= 1 (length results)))
            (should (eq 'cancelled (plist-get (car results) :status)))
            (funcall guild-success '(((id . "stale") (name . "Stale"))))
            (funcall private-success '(((id . "stale-dm") (type . 1))))
            (should (= 1 (length results)))
            (should-not (disco-state-guilds))
            (should-not (disco-state-private-channels)))))
    (disco-directory-reset)
    (disco-state-reset)))

(ert-deftest disco-directory-guild-load-is-coalesced-and-marks-snapshot-complete ()
  (disco-state-reset)
  (disco-directory-reset)
  (disco-state-set-guilds '(((id . "g1") (name . "Guild"))))
  (let ((calls 0)
        success)
    (cl-letf (((symbol-function 'disco-api-guild-channels-async)
               (lambda (_guild-id &rest args)
                 (cl-incf calls)
                 (setq success (plist-get args :on-success)))))
      (should (eq 'loading (disco-directory-load-guild-async "g1")))
      (should (eq 'loading (disco-directory-load-guild-async "g1")))
      (should (= calls 1))
      (funcall success '(((id . "c1") (guild_id . "g1") (type . 0)
                          (permissions . "1024"))))
      (should (eq 'loaded (disco-directory-guild-status "g1")))
      (should (disco-state-guild-channels-loaded-p "g1"))
      (should (equal "c1"
                     (alist-get 'id (car (disco-state-guild-channels "g1"))))))))

(ert-deftest disco-directory-old-session-response-cannot-overwrite-gateway-state ()
  (unwind-protect
      (let ((disco-gateway--session-generation 10))
        (disco-state-reset)
        (disco-directory-reset)
        (disco-state-set-guilds '(((id . "g1") (name . "Guild"))))
        (let (success)
          (cl-letf (((symbol-function 'disco-api-guild-channels-async)
                     (lambda (_guild-id &rest args)
                       (setq success (plist-get args :on-success)))))
            (disco-directory-load-guild-async "g1")
            ;; A new READY session publishes native access before the old REST
            ;; request returns.
            (cl-incf disco-gateway--session-generation)
            (disco-state-upsert-gateway-channel
             `((id . "c1") (guild_id . "g1") (type . 0)
               (flags . ,disco-channel-flag-obfuscated)))
            (funcall success
                     '(((id . "c1") (guild_id . "g1") (type . 0)
                        (permissions . "1024"))))
            (should (eq 'hidden (disco-state-channel-access "c1")))
            (should-not (disco-state-channel-viewable-p
                         (disco-state-channel "c1") nil))
            (should (eq 'unloaded
                        (disco-directory-guild-status "g1"))))))
    (disco-directory-reset)
    (disco-state-reset)))

(ert-deftest disco-directory-guild-load-rejects-unresolved-permissions ()
  (disco-state-reset)
  (disco-directory-reset)
  (disco-state-set-guilds '(((id . "g1") (name . "Guild"))))
  (let (success emitted)
    (let ((disco-directory-event-hook
           (list (lambda (event) (setq emitted event)))))
      (cl-letf (((symbol-function 'disco-api-guild-channels-async)
                 (lambda (_guild-id &rest args)
                   (setq success (plist-get args :on-success)))))
        (disco-directory-load-guild-async "g1")
        (funcall success '(((id . "c1") (guild_id . "g1") (type . 0))))
        (should (eq 'error (disco-directory-guild-status "g1")))
        (should-not (disco-state-guild-channels-loaded-p "g1"))
        (should-not (disco-state-channel "c1"))
        (should (eq 'guild-error (plist-get emitted :type)))
        (should (eq 'unresolved-channel-permissions
                    (plist-get (plist-get emitted :error) :kind)))
        (should (equal '("c1")
                       (plist-get (plist-get emitted :error)
                                  :channel-ids)))))))

(ert-deftest disco-directory-guild-load-error-is-explicit-and-retryable ()
  (disco-state-reset)
  (disco-directory-reset)
  (disco-state-set-guilds '(((id . "g1") (name . "Guild"))))
  (let ((calls 0)
        failure)
    (cl-letf (((symbol-function 'disco-api-guild-channels-async)
               (lambda (_guild-id &rest args)
                 (cl-incf calls)
                 (setq failure (plist-get args :on-error)))))
      (disco-directory-load-guild-async "g1")
      (funcall failure '(:status 500))
      (should (eq 'error (disco-directory-guild-status "g1")))
      (disco-directory-load-guild-async "g1")
      (should (= calls 2)))))

(ert-deftest disco-directory-parent-thread-loads-one-page-then-explicit-more ()
  (disco-directory-test--seed-visible-forum)
  (let (cursors events)
    (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
               (lambda (_parent-id &rest args)
                 (let ((cursor (plist-get args :max-id)))
                   (should (eq :false (plist-get args :archived)))
                   (should (eq 'creation-time (plist-get args :sort-by)))
                   (should (eq 'desc (plist-get args :sort-order)))
                   (push cursor cursors)
                   (funcall
                    (plist-get args :on-success)
                    (if cursor
                        '((threads . (((id . "100")
                                      (parent_id . "forum") (type . 11))))
                          (first_messages
                           . (((id . "starter-old")
                               (channel_id . "100")
                               (content . "older preview"))))
                          (has_more . :false)
                          (total_results . 1))
                      '((threads . (((id . "200")
                                    (parent_id . "forum") (type . 11))))
                        (first_messages
                         . (((id . "starter-new")
                             (channel_id . "200")
                             (content . "preview"))))
                        (has_more . t)
                        (total_results . 2)))))))
              (disco-directory-event-hook
               (list (lambda (event) (push (plist-get event :type) events)))))
      (should (eq 'loading
                  (disco-directory-load-parent-threads-async "forum")))
      ;; Initial expansion owns and commits one page only.
      (should (equal '(nil) (nreverse cursors)))
      (let ((state (disco-directory-parent-threads-state "forum")))
        (should (eq 'loaded (plist-get state :status)))
        (should (equal '("200") (plist-get state :thread-ids)))
        (should (equal "200" (plist-get state :next-cursor)))
        (should (= 2 (plist-get state :total))))
      (should (equal "preview"
                     (alist-get 'content
                                (car (disco-state-messages "200")))))
      (should (eq 'loading
                  (disco-directory-load-more-parent-threads-async "forum")))
      (should (equal '(nil "200") (nreverse cursors)))
      (let ((state (disco-directory-parent-threads-state "forum")))
        (should (eq 'loaded (plist-get state :status)))
        (should-not (plist-get state :next-cursor))
        (should (= 2 (length (plist-get state :thread-ids))))
        ;; The first page's authoritative total is stable across pagination.
        (should (= 2 (plist-get state :total)))
        (should (equal '("200" "100")
                       (plist-get state :thread-ids))))
      (should (equal '(parent-threads-loading
                       parent-threads-loaded
                       parent-threads-loading
                       parent-threads-loaded)
                     (nreverse events))))))

(ert-deftest disco-directory-parent-thread-load-coalesces-and-force-supersedes ()
  (disco-directory-test--seed-visible-forum)
  (let ((calls 0) callbacks)
    (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
               (lambda (_parent-id &rest args)
                 (cl-incf calls)
                 (push (plist-get args :on-success) callbacks))))
      (disco-directory-load-parent-threads-async "forum")
      (disco-directory-load-parent-threads-async "forum")
      (should (= 1 calls))
      (disco-directory-load-parent-threads-async "forum" :force t)
      (should (= 2 calls))
      (funcall (cadr callbacks)
               '((threads . (((id . "stale") (parent_id . "forum")
                              (type . 11))))
                 (has_more . :false)))
      (should-not (disco-state-channel "stale"))
      (funcall (car callbacks)
               '((threads . (((id . "fresh") (parent_id . "forum")
                              (type . 11))))
                 (has_more . :false)))
      (should (equal '("fresh")
                     (plist-get
                      (disco-directory-parent-threads-state "forum")
                      :thread-ids))))))

(ert-deftest disco-directory-parent-thread-page-cursor-must-move-older ()
  (disco-directory-test--seed-visible-forum)
  (puthash "forum"
           '(:status loaded :guild-id "guild" :thread-ids ("300")
             :next-cursor "200" :total 4)
           disco-directory--parent-thread-state)
  (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
             (lambda (_parent-id &rest args)
               (funcall
                (plist-get args :on-success)
                '((threads . (((id . "250")
                               (parent_id . "forum") (type . 11))))
                  (has_more . t))))))
    (disco-directory-load-more-parent-threads-async "forum")
    (let ((state (disco-directory-parent-threads-state "forum")))
      (should (eq 'error (plist-get state :status)))
      (should (eq 'invalid-thread-search-cursor
                  (plist-get (plist-get state :error) :kind))))
    (should-not (disco-state-channel "250"))))

(ert-deftest disco-directory-parent-thread-response-drops-invalid-parent-state ()
  (disco-directory-test--seed-visible-forum)
  (let (success)
    (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
               (lambda (_parent-id &rest args)
                 (setq success (plist-get args :on-success)))))
      (disco-directory-load-parent-threads-async "forum")
      (should (eq 'loading
                  (plist-get
                   (disco-directory-parent-threads-state "forum") :status)))
      (disco-state-upsert-gateway-channel
       `((id . "forum") (guild_id . "guild") (type . 15)
         (flags . ,disco-channel-flag-obfuscated)))
      (funcall success
               '((threads . (((id . "hidden-thread")
                              (parent_id . "forum") (type . 11))))
                 (has_more . :false)))
      (should (eq 'unloaded
                  (plist-get
                   (disco-directory-parent-threads-state "forum") :status)))
      (should-not (disco-state-channel "hidden-thread")))))

(ert-deftest disco-directory-parent-thread-append-error-preserves-and-retries ()
  (disco-directory-test--seed-visible-forum)
  (let (requests)
    (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
               (lambda (_parent-id &rest args) (push args requests))))
      (disco-directory-load-parent-threads-async "forum")
      (funcall (plist-get (car requests) :on-success)
               '((threads . (((id . "200")
                              (parent_id . "forum") (type . 11))))
                 (first_messages . nil)
                 (has_more . t)
                 (total_results . 40)))
      (disco-directory-load-more-parent-threads-async "forum")
      (should (equal "200" (plist-get (car requests) :max-id)))
      (funcall (plist-get (car requests) :on-error)
               '(:status 0 :message "request failed"))
      (let ((state (disco-directory-parent-threads-state "forum")))
        (should (eq 'error (plist-get state :status)))
        (should (equal '("200") (plist-get state :thread-ids)))
        (should (equal "200" (plist-get state :next-cursor)))
        (should (= 40 (plist-get state :total))))
      ;; Ensure does not accidentally restart from page one after an error.
      (should (eq 'error
                  (disco-directory-load-parent-threads-async "forum")))
      (should (= 2 (length requests)))
      (disco-directory-retry-parent-threads-async "forum")
      (should (= 3 (length requests)))
      (should (equal "200" (plist-get (car requests) :max-id)))
      (let ((state (disco-directory-parent-threads-state "forum")))
        (should (eq 'loading (plist-get state :status)))
        (should (eq 'append (plist-get state :mode)))
        (should (equal '("200") (plist-get state :thread-ids))))
      (funcall (plist-get (car requests) :on-success)
               '((threads . (((id . "100")
                              (parent_id . "forum") (type . 11))))
                 (first_messages
                  . (((id . "starter-second") (channel_id . "100"))))
                 (has_more . :false)))
      (let ((state (disco-directory-parent-threads-state "forum")))
        (should (eq 'loaded (plist-get state :status)))
        (should (equal '("200" "100")
                       (plist-get state :thread-ids)))
        (should-not (plist-get state :next-cursor))))))

(ert-deftest disco-directory-parent-thread-force-preserves-snapshot-until-commit ()
  (disco-directory-test--seed-visible-forum)
  (let (requests)
    (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
               (lambda (_parent-id &rest args) (push args requests))))
      (disco-directory-load-parent-threads-async "forum")
      (funcall (plist-get (car requests) :on-success)
               '((threads . (((id . "old")
                              (parent_id . "forum") (type . 11))))
                 (has_more . t)
                 (total_results . 10)))
      (disco-directory-load-parent-threads-async "forum" :force t)
      (should-not (plist-get (car requests) :max-id))
      (let ((state (disco-directory-parent-threads-state "forum")))
        (should (eq 'loading (plist-get state :status)))
        (should (eq 'replace (plist-get state :mode)))
        (should (equal '("old") (plist-get state :thread-ids)))
        (should (equal "old" (plist-get state :next-cursor)))
        (should (= 10 (plist-get state :total))))
      ;; A failed refresh retains the committed page and its pagination cursor.
      (funcall (plist-get (car requests) :on-error) '(:status 503))
      (let ((state (disco-directory-parent-threads-state "forum")))
        (should (eq 'error (plist-get state :status)))
        (should (equal '("old") (plist-get state :thread-ids)))
        (should (equal "old" (plist-get state :next-cursor))))
      (disco-directory-retry-parent-threads-async "forum")
      ;; Retry repeats the failed replace cursor, not the committed next cursor.
      (should-not (plist-get (car requests) :max-id))
      (funcall (plist-get (car requests) :on-success)
               '((threads . (((id . "fresh")
                              (parent_id . "forum") (type . 11))))
                 (has_more . :false)
                 (total_results . 1)))
      (let ((state (disco-directory-parent-threads-state "forum")))
        (should (eq 'loaded (plist-get state :status)))
        (should (equal '("fresh") (plist-get state :thread-ids)))
        (should (= 1 (plist-get state :total)))))))

(ert-deftest disco-directory-parent-thread-load-retries-pending-index ()
  (disco-directory-test--seed-visible-forum)
  (let ((calls 0) scheduled)
    (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
               (lambda (_parent-id &rest args)
                 (cl-incf calls)
                 (funcall (plist-get args :on-success)
                          (if (= calls 1)
                              '((code . 110000) (retry_after . 2))
                            '((threads . nil) (has_more . :false))))))
              ((symbol-function 'run-at-time)
               (lambda (delay _repeat function &rest args)
                 (setq scheduled (list delay function args))
                 :timer)))
      (disco-directory-load-parent-threads-async "forum")
      (let ((state (disco-directory-parent-threads-state "forum")))
        (should (eq 'loading (plist-get state :status)))
        (should (eq 'indexing (plist-get state :phase))))
      (should (= 2 (car scheduled)))
      (apply (cadr scheduled) (caddr scheduled))
      (should (= 2 calls))
      (should (eq 'loaded
                  (plist-get
                   (disco-directory-parent-threads-state "forum") :status))))))

(ert-deftest disco-directory-parent-thread-empty-snapshot-ignores-stale-index ()
  (disco-directory-test--seed-visible-forum)
  (disco-state-upsert-channel
   '((id . "stale") (guild_id . "guild")
     (parent_id . "forum") (type . 11)))
  (should (disco-state-parent-threads "forum"))
  (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
             (lambda (_parent-id &rest args)
               (funcall (plist-get args :on-success)
                        '((threads . nil) (first_messages . nil)
                          (has_more . :false) (total_results . 0))))))
    (disco-directory-load-parent-threads-async "forum")
    (let ((state (disco-directory-parent-threads-state "forum")))
      (should (eq 'loaded (plist-get state :status)))
      (should-not (plist-get state :thread-ids))
      (should (= 0 (plist-get state :total))))
    (should-not (disco-directory-parent-threads "forum"))))

(ert-deftest disco-directory-parent-thread-response-identity-is-strict ()
  (disco-directory-test--seed-visible-forum)
  (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
             (lambda (_parent-id &rest args)
               (funcall
                (plist-get args :on-success)
                '((threads . (((id . "wrong")
                               (parent_id . "another-forum") (type . 11))))
                  (has_more . :false))))))
    (disco-directory-load-parent-threads-async "forum")
    (let ((state (disco-directory-parent-threads-state "forum")))
      (should (eq 'error (plist-get state :status)))
      (should (eq 'invalid-thread-search-response
                  (plist-get (plist-get state :error) :kind))))
    (should-not (disco-state-channel "wrong"))))

(ert-deftest disco-directory-parent-thread-endpoint-proof-is-parent-scoped ()
  (disco-directory-test--seed-visible-forum)
  (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
             (lambda (_parent-id &rest args)
               (funcall
                (plist-get args :on-success)
                '((threads . (((id . "listed")
                               (parent_id . "forum") (type . 11))))
                  (has_more . :false))))))
    (disco-directory-load-parent-threads-async "forum"))
  ;; Search inclusion resolves only this thread's otherwise unknown access.
  (should-not (disco-state-channel-viewable-p
               (disco-state-channel "listed") nil))
  (should (disco-directory-parent-thread-viewable-p "forum" "listed"))
  (disco-state-upsert-channel
   '((id . "unlisted") (guild_id . "guild")
     (parent_id . "forum") (type . 11)))
  (should-not (disco-directory-parent-thread-viewable-p "forum" "unlisted"))
  ;; Authoritative Gateway hiding still wins over endpoint inclusion.
  (disco-state-upsert-gateway-channel
   `((id . "listed") (guild_id . "guild") (parent_id . "forum")
     (type . 11) (flags . ,disco-channel-flag-obfuscated)))
  (should-not (disco-directory-parent-thread-viewable-p "forum" "listed"))
  ;; A later parent denial also invalidates every scoped child proof.
  (disco-state-upsert-gateway-channel
   `((id . "forum") (guild_id . "guild") (type . 15)
     (flags . ,disco-channel-flag-obfuscated)))
  (should-not (disco-directory-parent-thread-viewable-p "forum" "listed")))

(ert-deftest disco-directory-parent-thread-inaccessible-parent-is-not-requested ()
  (disco-state-reset)
  (disco-directory-reset)
  (disco-state-set-guilds '(((id . "guild") (name . "Guild"))))
  (disco-state-put-channels
   "guild" '(((id . "forum") (guild_id . "guild") (type . 15))))
  (let ((calls 0))
    (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
               (lambda (&rest _args) (cl-incf calls))))
      (should-error (disco-directory-load-parent-threads-async "forum"))
      (should (= 0 calls)))))

(ert-deftest disco-directory-parent-thread-old-session-response-is-ignored ()
  (unwind-protect
      (let ((disco-gateway--session-generation 50))
        (disco-directory-test--seed-visible-forum)
        (let (success)
          (cl-letf (((symbol-function 'disco-api-channel-search-threads-async)
                     (lambda (_parent-id &rest args)
                       (setq success (plist-get args :on-success)))))
            (disco-directory-load-parent-threads-async "forum")
            (cl-incf disco-gateway--session-generation)
            (disco-directory-parent-threads-state "forum")
            (funcall success
                     '((threads . (((id . "stale") (parent_id . "forum")
                                    (type . 11))))
                       (has_more . :false)))
            (should-not (disco-state-channel "stale"))
            (should (eq 'unloaded
                        (plist-get
                         (disco-directory-parent-threads-state "forum")
                         :status))))))
    (disco-directory-reset)
    (disco-state-reset)))

(provide 'disco-directory-test)

;;; disco-directory-test.el ends here
